-- Schema: tnra

-- DROP SCHEMA tnra;

CREATE SCHEMA tnra AUTHORIZATION elf_admin;

COMMENT ON SCHEMA misc IS 'Schemata für Thema TransportNetwork-Rail';
  
-- == Tabellen =====

CREATE TABLE tnra.nominaltrackgauge (
    gml_id text,
    identifier text,
    identifier_codespace text,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    nominalgauge numeric,
    nominalgauge_nilreason text,
    nominalgauge_uom text,
    nominalgauge_nil boolean,
    nominalgaugecategory text,
    nominalgaugecategory_nilreason text,
    nominalgaugecategory_nil boolean,
    CONSTRAINT nominaltrackgauge_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnra.nominaltrackgauge OWNER TO elf_admin;

CREATE TABLE tnra.nominaltrackgauge_networkref (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.nominaltrackgauge ON DELETE CASCADE,
    num integer not null,
    nilreason text,
    nil boolean,
    simplelinearreference_element_owns boolean,
    simplelinearreference_element_nilreason text,
    simplelinearreference_element_remoteschema text,
    simplelinearreference_element_fk text,
    simplelinearreference_element_href text,
    simplelinearreference_applicabledirection_owns boolean,
    simplelinearreference_applicabledirection_nilreason text,
    simplelinearreference_applicabledirection_remoteschema text,
    simplelinearreference_applicabledirection_nil boolean,
    simplelinearreference_applicabledirection_fk text,
    simplelinearreference_applicabledirection_href text,
    simplelinearreference_fromposition numeric,
    simplelinearreference_fromposition_uom text,
    simplelinearreference_toposition numeric,
    simplelinearreference_toposition_uom text,
    simplelinearreference_offset numeric,
    simplelinearreference_offset_nilreason text,
    simplelinearreference_offset_uom text,
    simplelinearreference_offset_nil boolean,
    simplepointreference_element_owns boolean,
    simplepointreference_element_nilreason text,
    simplepointreference_element_remoteschema text,
    simplepointreference_element_fk text,
    simplepointreference_element_href text,
    simplepointreference_applicabledirection_owns boolean,
    simplepointreference_applicabledirection_nilreason text,
    simplepointreference_applicabledirection_remoteschema text,
    simplepointreference_applicabledirection_nil boolean,
    simplepointreference_applicabledirection_fk text,
    simplepointreference_applicabledirection_href text,
    simplepointreference_atposition numeric,
    simplepointreference_atposition_uom text,
    simplepointreference_offset numeric,
    simplepointreference_offset_nilreason text,
    simplepointreference_offset_uom text,
    simplepointreference_offset_nil boolean,
    linkreference_element_owns boolean,
    linkreference_element_nilreason text,
    linkreference_element_remoteschema text,
    linkreference_element_fk text,
    linkreference_element_href text,
    linkreference_applicabledirection_owns boolean,
    linkreference_applicabledirection_nilreason text,
    linkreference_applicabledirection_remoteschema text,
    linkreference_applicabledirection_nil boolean,
    linkreference_applicabledirection_fk text,
    linkreference_applicabledirection_href text,
    networkreference_element_owns boolean,
    networkreference_element_nilreason text,
    networkreference_element_remoteschema text,
    networkreference_element_fk text,
    networkreference_element_href text
);
ALTER TABLE tnra.nominaltrackgauge_networkref OWNER TO elf_admin;

CREATE TABLE tnra.numberoftracks (
    gml_id text,
    identifier text,
    identifier_codespace text,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    minmaxnumberoftracks text,
    minmaxnumberoftracks_nilreason text,
    minmaxnumberoftracks_nil boolean,
    numberoftracks integer,
    CONSTRAINT numberoftracks_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnra.numberoftracks OWNER TO elf_admin;

CREATE TABLE tnra.numberoftracks_networkref (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.numberoftracks ON DELETE CASCADE,
    num integer not null,
    nilreason text,
    nil boolean,
    simplelinearreference_element_owns boolean,
    simplelinearreference_element_nilreason text,
    simplelinearreference_element_remoteschema text,
    simplelinearreference_element_fk text,
    simplelinearreference_element_href text,
    simplelinearreference_applicabledirection_owns boolean,
    simplelinearreference_applicabledirection_nilreason text,
    simplelinearreference_applicabledirection_remoteschema text,
    simplelinearreference_applicabledirection_nil boolean,
    simplelinearreference_applicabledirection_fk text,
    simplelinearreference_applicabledirection_href text,
    simplelinearreference_fromposition numeric,
    simplelinearreference_fromposition_uom text,
    simplelinearreference_toposition numeric,
    simplelinearreference_toposition_uom text,
    simplelinearreference_offset numeric,
    simplelinearreference_offset_nilreason text,
    simplelinearreference_offset_uom text,
    simplelinearreference_offset_nil boolean,
    simplepointreference_element_owns boolean,
    simplepointreference_element_nilreason text,
    simplepointreference_element_remoteschema text,
    simplepointreference_element_fk text,
    simplepointreference_element_href text,
    simplepointreference_applicabledirection_owns boolean,
    simplepointreference_applicabledirection_nilreason text,
    simplepointreference_applicabledirection_remoteschema text,
    simplepointreference_applicabledirection_nil boolean,
    simplepointreference_applicabledirection_fk text,
    simplepointreference_applicabledirection_href text,
    simplepointreference_atposition numeric,
    simplepointreference_atposition_uom text,
    simplepointreference_offset numeric,
    simplepointreference_offset_nilreason text,
    simplepointreference_offset_uom text,
    simplepointreference_offset_nil boolean,
    linkreference_element_owns boolean,
    linkreference_element_nilreason text,
    linkreference_element_remoteschema text,
    linkreference_element_fk text,
    linkreference_element_href text,
    linkreference_applicabledirection_owns boolean,
    linkreference_applicabledirection_nilreason text,
    linkreference_applicabledirection_remoteschema text,
    linkreference_applicabledirection_nil boolean,
    linkreference_applicabledirection_fk text,
    linkreference_applicabledirection_href text,
    networkreference_element_owns boolean,
    networkreference_element_nilreason text,
    networkreference_element_remoteschema text,
    networkreference_element_fk text,
    networkreference_element_href text
);
ALTER TABLE tnra.numberoftracks_networkref OWNER TO elf_admin;

CREATE TABLE tnra.railwayarea (
    gml_id text,
    identifier text,
    identifier_codespace text,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    geometry_nilreason text,
    geometry_remoteschema text,
    geometry_owns boolean,
    geographicalname_nilreason text,
    geographicalname_nil boolean,
    geographicalname_language text,
    geographicalname_language_nilreason text,
    geographicalname_language_nil boolean,
    geographicalname_nativeness_owns boolean,
    geographicalname_nativeness_nilreason text,
    geographicalname_nativeness_remoteschema text,
    geographicalname_nativeness_nil boolean,
    geographicalname_nativeness_fk text,
    geographicalname_nativeness_href text,
    geographicalname_namestatus_owns boolean,
    geographicalname_namestatus_nilreason text,
    geographicalname_namestatus_remoteschema text,
    geographicalname_namestatus_nil boolean,
    geographicalname_namestatus_fk text,
    geographicalname_namestatus_href text,
    geographicalname_sourceofname text,
    geographicalname_sourceofname_nilreason text,
    geographicalname_sourceofname_nil boolean,
    geographicalname_pronunciation_nilreason text,
    geographicalname_pronunciation_nil boolean,
    geographicalname_pronunciationofname_soundlink text,
    geographicalname_pronunciationofname_soundlink_nilreason text,
    geographicalname_pronunciationofname_soundlink_nil boolean,
    geographicalname_pronunciationofname_pronunciationipa text,
    geographicalname_pronunciationofname_pronunciationipa_nilreason text,
    geographicalname_pronunciationofname_pronunciationipa_nil boolean,
    geographicalname_grammaticalgender_owns boolean,
    geographicalname_grammaticalgender_nilreason text,
    geographicalname_grammaticalgender_remoteschema text,
    geographicalname_grammaticalgender_nil boolean,
    geographicalname_grammaticalgender_fk text,
    geographicalname_grammaticalgender_href text,
    geographicalname_grammaticalnumber_owns boolean,
    geographicalname_grammaticalnumber_nilreason text,
    geographicalname_grammaticalnumber_remoteschema text,
    geographicalname_grammaticalnumber_nil boolean,
    geographicalname_grammaticalnumber_fk text,
    geographicalname_grammaticalnumber_href text,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    CONSTRAINT railwayarea_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnra.railwayarea OWNER TO elf_admin;

CREATE TABLE tnra.railwayarea_innetwork (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwayarea ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnra.railwayarea_innetwork OWNER TO elf_admin;

SELECT ADDGEOMETRYCOLUMN('tnra', 'railwayarea','geometry_value','4258','GEOMETRY', 2);
CREATE INDEX railwayarea_geometry_idx ON tnra.railwayarea USING GIST (geometry_value);

CREATE TABLE tnra.railwayarea_geographicalname_spelling (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwayarea ON DELETE CASCADE,
    num integer not null,
    geographicalname_spellingofname_text text,
    geographicalname_spellingofname_script text,
    geographicalname_spellingofname_script_nilreason text,
    geographicalname_spellingofname_script_nil boolean,
    geographicalname_spellingofname_transliterationscheme text,
    geographicalname_spellingofname_transliterationscheme_nilreason text,
    geographicalname_spellingofname_transliterationscheme_nil boolean
);
ALTER TABLE tnra.railwayarea_geographicalname_spelling OWNER TO elf_admin;

CREATE TABLE tnra.railwayline (
    gml_id text,
    identifier text,
    identifier_codespace text,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    geographicalname_nilreason text,
    geographicalname_nil boolean,
    geographicalname_language text,
    geographicalname_language_nilreason text,
    geographicalname_language_nil boolean,
    geographicalname_nativeness_owns boolean,
    geographicalname_nativeness_nilreason text,
    geographicalname_nativeness_remoteschema text,
    geographicalname_nativeness_nil boolean,
    geographicalname_nativeness_fk text,
    geographicalname_nativeness_href text,
    geographicalname_namestatus_owns boolean,
    geographicalname_namestatus_nilreason text,
    geographicalname_namestatus_remoteschema text,
    geographicalname_namestatus_nil boolean,
    geographicalname_namestatus_fk text,
    geographicalname_namestatus_href text,
    geographicalname_sourceofname text,
    geographicalname_sourceofname_nilreason text,
    geographicalname_sourceofname_nil boolean,
    geographicalname_pronunciation_nilreason text,
    geographicalname_pronunciation_nil boolean,
    geographicalname_pronunciationofname_soundlink text,
    geographicalname_pronunciationofname_soundlink_nilreason text,
    geographicalname_pronunciationofname_soundlink_nil boolean,
    geographicalname_pronunciationofname_pronunciationipa text,
    geographicalname_pronunciationofname_pronunciationipa_nilreason text,
    geographicalname_pronunciationofname_pronunciationipa_nil boolean,
    geographicalname_grammaticalgender_owns boolean,
    geographicalname_grammaticalgender_nilreason text,
    geographicalname_grammaticalgender_remoteschema text,
    geographicalname_grammaticalgender_nil boolean,
    geographicalname_grammaticalgender_fk text,
    geographicalname_grammaticalgender_href text,
    geographicalname_grammaticalnumber_owns boolean,
    geographicalname_grammaticalnumber_nilreason text,
    geographicalname_grammaticalnumber_remoteschema text,
    geographicalname_grammaticalnumber_nil boolean,
    geographicalname_grammaticalnumber_fk text,
    geographicalname_grammaticalnumber_href text,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    railwaylinecode text,
    railwaylinecode_nilreason text,
    railwaylinecode_nil boolean,
    CONSTRAINT railwayline_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnra.railwayline OWNER TO elf_admin;

CREATE TABLE tnra.railwayline_innetwork (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwayline ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnra.railwayline_innetwork OWNER TO elf_admin;

CREATE TABLE tnra.railwayline_link (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwayline ON DELETE CASCADE,
    num integer not null,
    nilreason text,
    remoteschema text,
    owns boolean,
    fk text,
    href text
);
ALTER TABLE tnra.railwayline_link OWNER TO elf_admin;

CREATE TABLE tnra.railwayline_geographicalname_spelling (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwayline ON DELETE CASCADE,
    num integer not null,
    geographicalname_spellingofname_text text,
    geographicalname_spellingofname_script text,
    geographicalname_spellingofname_script_nilreason text,
    geographicalname_spellingofname_script_nil boolean,
    geographicalname_spellingofname_transliterationscheme text,
    geographicalname_spellingofname_transliterationscheme_nilreason text,
    geographicalname_spellingofname_transliterationscheme_nil boolean
);
ALTER TABLE tnra.railwayline_geographicalname_spelling OWNER TO elf_admin;

CREATE TABLE tnra.railwayline_post (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwayline ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnra.railwayline_post OWNER TO elf_admin;

CREATE TABLE tnra.railwaylinksequence (
    gml_id text,
    identifier text,
    identifier_codespace text,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    geographicalname_nilreason text,
    geographicalname_nil boolean,
    geographicalname_language text,
    geographicalname_language_nilreason text,
    geographicalname_language_nil boolean,
    geographicalname_nativeness_owns boolean,
    geographicalname_nativeness_nilreason text,
    geographicalname_nativeness_remoteschema text,
    geographicalname_nativeness_nil boolean,
    geographicalname_nativeness_fk text,
    geographicalname_nativeness_href text,
    geographicalname_namestatus_owns boolean,
    geographicalname_namestatus_nilreason text,
    geographicalname_namestatus_remoteschema text,
    geographicalname_namestatus_nil boolean,
    geographicalname_namestatus_fk text,
    geographicalname_namestatus_href text,
    geographicalname_sourceofname text,
    geographicalname_sourceofname_nilreason text,
    geographicalname_sourceofname_nil boolean,
    geographicalname_pronunciation_nilreason text,
    geographicalname_pronunciation_nil boolean,
    geographicalname_pronunciationofname_soundlink text,
    geographicalname_pronunciationofname_soundlink_nilreason text,
    geographicalname_pronunciationofname_soundlink_nil boolean,
    geographicalname_pronunciationofname_pronunciationipa text,
    geographicalname_pronunciationofname_pronunciationipa_nilreason text,
    geographicalname_pronunciationofname_pronunciationipa_nil boolean,
    geographicalname_grammaticalgender_owns boolean,
    geographicalname_grammaticalgender_nilreason text,
    geographicalname_grammaticalgender_remoteschema text,
    geographicalname_grammaticalgender_nil boolean,
    geographicalname_grammaticalgender_fk text,
    geographicalname_grammaticalgender_href text,
    geographicalname_grammaticalnumber_owns boolean,
    geographicalname_grammaticalnumber_nilreason text,
    geographicalname_grammaticalnumber_remoteschema text,
    geographicalname_grammaticalnumber_nil boolean,
    geographicalname_grammaticalnumber_fk text,
    geographicalname_grammaticalnumber_href text,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    CONSTRAINT railwaylinksequence_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnra.railwaylinksequence OWNER TO elf_admin;

CREATE TABLE tnra.railwaylinksequence_innetwork (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwaylinksequence ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnra.railwaylinksequence_innetwork OWNER TO elf_admin;

CREATE TABLE tnra.railwaylinksequence_link (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwaylinksequence ON DELETE CASCADE,
    num integer not null,
    directedlink_direction text,
    directedlink_link_owns boolean,
    directedlink_link_nilreason text,
    directedlink_link_remoteschema text,
    directedlink_link_fk text,
    directedlink_link_href text
);
ALTER TABLE tnra.railwaylinksequence_link OWNER TO elf_admin;

CREATE TABLE tnra.railwaylinksequence_geographicalname_spelling (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwaylinksequence ON DELETE CASCADE,
    num integer not null,
    geographicalname_spellingofname_text text,
    geographicalname_spellingofname_script text,
    geographicalname_spellingofname_script_nilreason text,
    geographicalname_spellingofname_script_nil boolean,
    geographicalname_spellingofname_transliterationscheme text,
    geographicalname_spellingofname_transliterationscheme_nilreason text,
    geographicalname_spellingofname_transliterationscheme_nil boolean
);
ALTER TABLE tnra.railwaylinksequence_geographicalname_spelling OWNER TO elf_admin;

CREATE TABLE tnra.railwaynode (
    gml_id text,
    identifier text,
    identifier_codespace text,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    geometry_nilreason text,
    geometry_remoteschema text,
    geometry_owns boolean,
    geographicalname_nilreason text,
    geographicalname_nil boolean,
    geographicalname_language text,
    geographicalname_language_nilreason text,
    geographicalname_language_nil boolean,
    geographicalname_nativeness_owns boolean,
    geographicalname_nativeness_nilreason text,
    geographicalname_nativeness_remoteschema text,
    geographicalname_nativeness_nil boolean,
    geographicalname_nativeness_fk text,
    geographicalname_nativeness_href text,
    geographicalname_namestatus_owns boolean,
    geographicalname_namestatus_nilreason text,
    geographicalname_namestatus_remoteschema text,
    geographicalname_namestatus_nil boolean,
    geographicalname_namestatus_fk text,
    geographicalname_namestatus_href text,
    geographicalname_sourceofname text,
    geographicalname_sourceofname_nilreason text,
    geographicalname_sourceofname_nil boolean,
    geographicalname_pronunciation_nilreason text,
    geographicalname_pronunciation_nil boolean,
    geographicalname_pronunciationofname_soundlink text,
    geographicalname_pronunciationofname_soundlink_nilreason text,
    geographicalname_pronunciationofname_soundlink_nil boolean,
    geographicalname_pronunciationofname_pronunciationipa text,
    geographicalname_pronunciationofname_pronunciationipa_nilreason text,
    geographicalname_pronunciationofname_pronunciationipa_nil boolean,
    geographicalname_grammaticalgender_owns boolean,
    geographicalname_grammaticalgender_nilreason text,
    geographicalname_grammaticalgender_remoteschema text,
    geographicalname_grammaticalgender_nil boolean,
    geographicalname_grammaticalgender_fk text,
    geographicalname_grammaticalgender_href text,
    geographicalname_grammaticalnumber_owns boolean,
    geographicalname_grammaticalnumber_nilreason text,
    geographicalname_grammaticalnumber_remoteschema text,
    geographicalname_grammaticalnumber_nil boolean,
    geographicalname_grammaticalnumber_fk text,
    geographicalname_grammaticalnumber_href text,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    formofnode_owns boolean,
    formofnode_nilreason text,
    formofnode_remoteschema text,
    formofnode_nil boolean,
    formofnode_fk text,
    formofnode_href text,
    CONSTRAINT railwaynode_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnra.railwaynode OWNER TO elf_admin;

CREATE TABLE tnra.railwaynode_innetwork (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwaynode ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnra.railwaynode_innetwork OWNER TO elf_admin;

SELECT ADDGEOMETRYCOLUMN('tnra', 'railwaynode','geometry_value','4258','GEOMETRY', 2);
CREATE INDEX railwaynode_geometry_idx ON tnra.railwaynode USING GIST (geometry_value);

CREATE TABLE tnra.railwaynode_spokeend (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwaynode ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnra.railwaynode_spokeend OWNER TO elf_admin;

CREATE TABLE tnra.railwaynode_spokestart (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwaynode ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnra.railwaynode_spokestart OWNER TO elf_admin;

CREATE TABLE tnra.railwaynode_geographicalname_spelling (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwaynode ON DELETE CASCADE,
    num integer not null,
    geographicalname_spellingofname_text text,
    geographicalname_spellingofname_script text,
    geographicalname_spellingofname_script_nilreason text,
    geographicalname_spellingofname_script_nil boolean,
    geographicalname_spellingofname_transliterationscheme text,
    geographicalname_spellingofname_transliterationscheme_nilreason text,
    geographicalname_spellingofname_transliterationscheme_nil boolean
);
ALTER TABLE tnra.railwaynode_geographicalname_spelling OWNER TO elf_admin;

CREATE TABLE tnra.railwaystationarea (
    gml_id text,
    identifier text,
    identifier_codespace text,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    geometry_nilreason text,
    geometry_remoteschema text,
    geometry_owns boolean,
    geographicalname_nilreason text,
    geographicalname_nil boolean,
    geographicalname_language text,
    geographicalname_language_nilreason text,
    geographicalname_language_nil boolean,
    geographicalname_nativeness_owns boolean,
    geographicalname_nativeness_nilreason text,
    geographicalname_nativeness_remoteschema text,
    geographicalname_nativeness_nil boolean,
    geographicalname_nativeness_fk text,
    geographicalname_nativeness_href text,
    geographicalname_namestatus_owns boolean,
    geographicalname_namestatus_nilreason text,
    geographicalname_namestatus_remoteschema text,
    geographicalname_namestatus_nil boolean,
    geographicalname_namestatus_fk text,
    geographicalname_namestatus_href text,
    geographicalname_sourceofname text,
    geographicalname_sourceofname_nilreason text,
    geographicalname_sourceofname_nil boolean,
    geographicalname_pronunciation_nilreason text,
    geographicalname_pronunciation_nil boolean,
    geographicalname_pronunciationofname_soundlink text,
    geographicalname_pronunciationofname_soundlink_nilreason text,
    geographicalname_pronunciationofname_soundlink_nil boolean,
    geographicalname_pronunciationofname_pronunciationipa text,
    geographicalname_pronunciationofname_pronunciationipa_nilreason text,
    geographicalname_pronunciationofname_pronunciationipa_nil boolean,
    geographicalname_grammaticalgender_owns boolean,
    geographicalname_grammaticalgender_nilreason text,
    geographicalname_grammaticalgender_remoteschema text,
    geographicalname_grammaticalgender_nil boolean,
    geographicalname_grammaticalgender_fk text,
    geographicalname_grammaticalgender_href text,
    geographicalname_grammaticalnumber_owns boolean,
    geographicalname_grammaticalnumber_nilreason text,
    geographicalname_grammaticalnumber_remoteschema text,
    geographicalname_grammaticalnumber_nil boolean,
    geographicalname_grammaticalnumber_fk text,
    geographicalname_grammaticalnumber_href text,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    CONSTRAINT railwaystationarea_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnra.railwaystationarea OWNER TO elf_admin;

CREATE TABLE tnra.railwaystationarea_innetwork (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwaystationarea ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnra.railwaystationarea_innetwork OWNER TO elf_admin;

SELECT ADDGEOMETRYCOLUMN('tnra', 'railwaystationarea','geometry_value','4258','GEOMETRY', 2);
CREATE INDEX railwaystationarea_geometry_idx ON tnra.railwaystationarea USING GIST (geometry_value);

CREATE TABLE tnra.railwaystationarea_geographicalname_spelling (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwaystationarea ON DELETE CASCADE,
    num integer not null,
    geographicalname_spellingofname_text text,
    geographicalname_spellingofname_script text,
    geographicalname_spellingofname_script_nilreason text,
    geographicalname_spellingofname_script_nil boolean,
    geographicalname_spellingofname_transliterationscheme text,
    geographicalname_spellingofname_transliterationscheme_nilreason text,
    geographicalname_spellingofname_transliterationscheme_nil boolean
);
ALTER TABLE tnra.railwaystationarea_geographicalname_spelling OWNER TO elf_admin;

CREATE TABLE tnra.railwaystationcode (
    gml_id text,
    identifier text,
    identifier_codespace text,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    stationcode text,
    CONSTRAINT railwaystationcode_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnra.railwaystationcode OWNER TO elf_admin;

CREATE TABLE tnra.railwaystationcode_networkref (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwaystationcode ON DELETE CASCADE,
    num integer not null,
    nilreason text,
    nil boolean,
    simplelinearreference_element_owns boolean,
    simplelinearreference_element_nilreason text,
    simplelinearreference_element_remoteschema text,
    simplelinearreference_element_fk text,
    simplelinearreference_element_href text,
    simplelinearreference_applicabledirection_owns boolean,
    simplelinearreference_applicabledirection_nilreason text,
    simplelinearreference_applicabledirection_remoteschema text,
    simplelinearreference_applicabledirection_nil boolean,
    simplelinearreference_applicabledirection_fk text,
    simplelinearreference_applicabledirection_href text,
    simplelinearreference_fromposition numeric,
    simplelinearreference_fromposition_uom text,
    simplelinearreference_toposition numeric,
    simplelinearreference_toposition_uom text,
    simplelinearreference_offset numeric,
    simplelinearreference_offset_nilreason text,
    simplelinearreference_offset_uom text,
    simplelinearreference_offset_nil boolean,
    simplepointreference_element_owns boolean,
    simplepointreference_element_nilreason text,
    simplepointreference_element_remoteschema text,
    simplepointreference_element_fk text,
    simplepointreference_element_href text,
    simplepointreference_applicabledirection_owns boolean,
    simplepointreference_applicabledirection_nilreason text,
    simplepointreference_applicabledirection_remoteschema text,
    simplepointreference_applicabledirection_nil boolean,
    simplepointreference_applicabledirection_fk text,
    simplepointreference_applicabledirection_href text,
    simplepointreference_atposition numeric,
    simplepointreference_atposition_uom text,
    simplepointreference_offset numeric,
    simplepointreference_offset_nilreason text,
    simplepointreference_offset_uom text,
    simplepointreference_offset_nil boolean,
    linkreference_element_owns boolean,
    linkreference_element_nilreason text,
    linkreference_element_remoteschema text,
    linkreference_element_fk text,
    linkreference_element_href text,
    linkreference_applicabledirection_owns boolean,
    linkreference_applicabledirection_nilreason text,
    linkreference_applicabledirection_remoteschema text,
    linkreference_applicabledirection_nil boolean,
    linkreference_applicabledirection_fk text,
    linkreference_applicabledirection_href text,
    networkreference_element_owns boolean,
    networkreference_element_nilreason text,
    networkreference_element_remoteschema text,
    networkreference_element_fk text,
    networkreference_element_href text
);
ALTER TABLE tnra.railwaystationcode_networkref OWNER TO elf_admin;

CREATE TABLE tnra.railwaytype (
    gml_id text,
    identifier text,
    identifier_codespace text,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    type_owns boolean,
    type_nilreason text,
    type_remoteschema text,
    type_fk text,
    type_href text,
    CONSTRAINT railwaytype_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnra.railwaytype OWNER TO elf_admin;

CREATE TABLE tnra.railwaytype_networkref (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwaytype ON DELETE CASCADE,
    num integer not null,
    nilreason text,
    nil boolean,
    simplelinearreference_element_owns boolean,
    simplelinearreference_element_nilreason text,
    simplelinearreference_element_remoteschema text,
    simplelinearreference_element_fk text,
    simplelinearreference_element_href text,
    simplelinearreference_applicabledirection_owns boolean,
    simplelinearreference_applicabledirection_nilreason text,
    simplelinearreference_applicabledirection_remoteschema text,
    simplelinearreference_applicabledirection_nil boolean,
    simplelinearreference_applicabledirection_fk text,
    simplelinearreference_applicabledirection_href text,
    simplelinearreference_fromposition numeric,
    simplelinearreference_fromposition_uom text,
    simplelinearreference_toposition numeric,
    simplelinearreference_toposition_uom text,
    simplelinearreference_offset numeric,
    simplelinearreference_offset_nilreason text,
    simplelinearreference_offset_uom text,
    simplelinearreference_offset_nil boolean,
    simplepointreference_element_owns boolean,
    simplepointreference_element_nilreason text,
    simplepointreference_element_remoteschema text,
    simplepointreference_element_fk text,
    simplepointreference_element_href text,
    simplepointreference_applicabledirection_owns boolean,
    simplepointreference_applicabledirection_nilreason text,
    simplepointreference_applicabledirection_remoteschema text,
    simplepointreference_applicabledirection_nil boolean,
    simplepointreference_applicabledirection_fk text,
    simplepointreference_applicabledirection_href text,
    simplepointreference_atposition numeric,
    simplepointreference_atposition_uom text,
    simplepointreference_offset numeric,
    simplepointreference_offset_nilreason text,
    simplepointreference_offset_uom text,
    simplepointreference_offset_nil boolean,
    linkreference_element_owns boolean,
    linkreference_element_nilreason text,
    linkreference_element_remoteschema text,
    linkreference_element_fk text,
    linkreference_element_href text,
    linkreference_applicabledirection_owns boolean,
    linkreference_applicabledirection_nilreason text,
    linkreference_applicabledirection_remoteschema text,
    linkreference_applicabledirection_nil boolean,
    linkreference_applicabledirection_fk text,
    linkreference_applicabledirection_href text,
    networkreference_element_owns boolean,
    networkreference_element_nilreason text,
    networkreference_element_remoteschema text,
    networkreference_element_fk text,
    networkreference_element_href text
);
ALTER TABLE tnra.railwaytype_networkref OWNER TO elf_admin;

CREATE TABLE tnra.railwayuse (
    gml_id text,
    identifier text,
    identifier_codespace text,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    use_owns boolean,
    use_nilreason text,
    use_remoteschema text,
    use_fk text,
    use_href text,
    CONSTRAINT railwayuse_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnra.railwayuse OWNER TO elf_admin;

CREATE TABLE tnra.railwayuse_networkref (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwayuse ON DELETE CASCADE,
    num integer not null,
    nilreason text,
    nil boolean,
    simplelinearreference_element_owns boolean,
    simplelinearreference_element_nilreason text,
    simplelinearreference_element_remoteschema text,
    simplelinearreference_element_fk text,
    simplelinearreference_element_href text,
    simplelinearreference_applicabledirection_owns boolean,
    simplelinearreference_applicabledirection_nilreason text,
    simplelinearreference_applicabledirection_remoteschema text,
    simplelinearreference_applicabledirection_nil boolean,
    simplelinearreference_applicabledirection_fk text,
    simplelinearreference_applicabledirection_href text,
    simplelinearreference_fromposition numeric,
    simplelinearreference_fromposition_uom text,
    simplelinearreference_toposition numeric,
    simplelinearreference_toposition_uom text,
    simplelinearreference_offset numeric,
    simplelinearreference_offset_nilreason text,
    simplelinearreference_offset_uom text,
    simplelinearreference_offset_nil boolean,
    simplepointreference_element_owns boolean,
    simplepointreference_element_nilreason text,
    simplepointreference_element_remoteschema text,
    simplepointreference_element_fk text,
    simplepointreference_element_href text,
    simplepointreference_applicabledirection_owns boolean,
    simplepointreference_applicabledirection_nilreason text,
    simplepointreference_applicabledirection_remoteschema text,
    simplepointreference_applicabledirection_nil boolean,
    simplepointreference_applicabledirection_fk text,
    simplepointreference_applicabledirection_href text,
    simplepointreference_atposition numeric,
    simplepointreference_atposition_uom text,
    simplepointreference_offset numeric,
    simplepointreference_offset_nilreason text,
    simplepointreference_offset_uom text,
    simplepointreference_offset_nil boolean,
    linkreference_element_owns boolean,
    linkreference_element_nilreason text,
    linkreference_element_remoteschema text,
    linkreference_element_fk text,
    linkreference_element_href text,
    linkreference_applicabledirection_owns boolean,
    linkreference_applicabledirection_nilreason text,
    linkreference_applicabledirection_remoteschema text,
    linkreference_applicabledirection_nil boolean,
    linkreference_applicabledirection_fk text,
    linkreference_applicabledirection_href text,
    networkreference_element_owns boolean,
    networkreference_element_nilreason text,
    networkreference_element_remoteschema text,
    networkreference_element_fk text,
    networkreference_element_href text
);
ALTER TABLE tnra.railwayuse_networkref OWNER TO elf_admin;

CREATE TABLE tnra.railwayyardarea (
    gml_id text,
    identifier text,
    identifier_codespace text,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    geometry_nilreason text,
    geometry_remoteschema text,
    geometry_owns boolean,
    geographicalname_nilreason text,
    geographicalname_nil boolean,
    geographicalname_language text,
    geographicalname_language_nilreason text,
    geographicalname_language_nil boolean,
    geographicalname_nativeness_owns boolean,
    geographicalname_nativeness_nilreason text,
    geographicalname_nativeness_remoteschema text,
    geographicalname_nativeness_nil boolean,
    geographicalname_nativeness_fk text,
    geographicalname_nativeness_href text,
    geographicalname_namestatus_owns boolean,
    geographicalname_namestatus_nilreason text,
    geographicalname_namestatus_remoteschema text,
    geographicalname_namestatus_nil boolean,
    geographicalname_namestatus_fk text,
    geographicalname_namestatus_href text,
    geographicalname_sourceofname text,
    geographicalname_sourceofname_nilreason text,
    geographicalname_sourceofname_nil boolean,
    geographicalname_pronunciation_nilreason text,
    geographicalname_pronunciation_nil boolean,
    geographicalname_pronunciationofname_soundlink text,
    geographicalname_pronunciationofname_soundlink_nilreason text,
    geographicalname_pronunciationofname_soundlink_nil boolean,
    geographicalname_pronunciationofname_pronunciationipa text,
    geographicalname_pronunciationofname_pronunciationipa_nilreason text,
    geographicalname_pronunciationofname_pronunciationipa_nil boolean,
    geographicalname_grammaticalgender_owns boolean,
    geographicalname_grammaticalgender_nilreason text,
    geographicalname_grammaticalgender_remoteschema text,
    geographicalname_grammaticalgender_nil boolean,
    geographicalname_grammaticalgender_fk text,
    geographicalname_grammaticalgender_href text,
    geographicalname_grammaticalnumber_owns boolean,
    geographicalname_grammaticalnumber_nilreason text,
    geographicalname_grammaticalnumber_remoteschema text,
    geographicalname_grammaticalnumber_nil boolean,
    geographicalname_grammaticalnumber_fk text,
    geographicalname_grammaticalnumber_href text,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    CONSTRAINT railwayyardarea_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnra.railwayyardarea OWNER TO elf_admin;

CREATE TABLE tnra.railwayyardarea_innetwork (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwayyardarea ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnra.railwayyardarea_innetwork OWNER TO elf_admin;

SELECT ADDGEOMETRYCOLUMN('tnra', 'railwayyardarea','geometry_value','4258','GEOMETRY', 2);
CREATE INDEX railwayyardarea_geometry_idx ON tnra.railwayyardarea USING GIST (geometry_value);

CREATE TABLE tnra.railwayyardarea_geographicalname_spelling (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwayyardarea ON DELETE CASCADE,
    num integer not null,
    geographicalname_spellingofname_text text,
    geographicalname_spellingofname_script text,
    geographicalname_spellingofname_script_nilreason text,
    geographicalname_spellingofname_script_nil boolean,
    geographicalname_spellingofname_transliterationscheme text,
    geographicalname_spellingofname_transliterationscheme_nilreason text,
    geographicalname_spellingofname_transliterationscheme_nil boolean
);
ALTER TABLE tnra.railwayyardarea_geographicalname_spelling OWNER TO elf_admin;

CREATE TABLE tnra.railwayyardnode (
    gml_id text,
    identifier text,
    identifier_codespace text,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    geometry_nilreason text,
    geometry_remoteschema text,
    geometry_owns boolean,
    geographicalname_nilreason text,
    geographicalname_nil boolean,
    geographicalname_language text,
    geographicalname_language_nilreason text,
    geographicalname_language_nil boolean,
    geographicalname_nativeness_owns boolean,
    geographicalname_nativeness_nilreason text,
    geographicalname_nativeness_remoteschema text,
    geographicalname_nativeness_nil boolean,
    geographicalname_nativeness_fk text,
    geographicalname_nativeness_href text,
    geographicalname_namestatus_owns boolean,
    geographicalname_namestatus_nilreason text,
    geographicalname_namestatus_remoteschema text,
    geographicalname_namestatus_nil boolean,
    geographicalname_namestatus_fk text,
    geographicalname_namestatus_href text,
    geographicalname_sourceofname text,
    geographicalname_sourceofname_nilreason text,
    geographicalname_sourceofname_nil boolean,
    geographicalname_pronunciation_nilreason text,
    geographicalname_pronunciation_nil boolean,
    geographicalname_pronunciationofname_soundlink text,
    geographicalname_pronunciationofname_soundlink_nilreason text,
    geographicalname_pronunciationofname_soundlink_nil boolean,
    geographicalname_pronunciationofname_pronunciationipa text,
    geographicalname_pronunciationofname_pronunciationipa_nilreason text,
    geographicalname_pronunciationofname_pronunciationipa_nil boolean,
    geographicalname_grammaticalgender_owns boolean,
    geographicalname_grammaticalgender_nilreason text,
    geographicalname_grammaticalgender_remoteschema text,
    geographicalname_grammaticalgender_nil boolean,
    geographicalname_grammaticalgender_fk text,
    geographicalname_grammaticalgender_href text,
    geographicalname_grammaticalnumber_owns boolean,
    geographicalname_grammaticalnumber_nilreason text,
    geographicalname_grammaticalnumber_remoteschema text,
    geographicalname_grammaticalnumber_nil boolean,
    geographicalname_grammaticalnumber_fk text,
    geographicalname_grammaticalnumber_href text,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    formofnode_owns boolean,
    formofnode_nilreason text,
    formofnode_remoteschema text,
    formofnode_nil boolean,
    formofnode_fk text,
    formofnode_href text,
    CONSTRAINT railwayyardnode_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnra.railwayyardnode OWNER TO elf_admin;

CREATE TABLE tnra.railwayyardnode_innetwork (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwayyardnode ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnra.railwayyardnode_innetwork OWNER TO elf_admin;

SELECT ADDGEOMETRYCOLUMN('tnra', 'railwayyardnode','geometry_value','4258','GEOMETRY', 2);
CREATE INDEX railwayyardnode_geometry_idx ON tnra.railwayyardnode USING GIST (geometry_value);

CREATE TABLE tnra.railwayyardnode_spokeend (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwayyardnode ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnra.railwayyardnode_spokeend OWNER TO elf_admin;

CREATE TABLE tnra.railwayyardnode_spokestart (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwayyardnode ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnra.railwayyardnode_spokestart OWNER TO elf_admin;

CREATE TABLE tnra.railwayyardnode_geographicalname_spelling (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwayyardnode ON DELETE CASCADE,
    num integer not null,
    geographicalname_spellingofname_text text,
    geographicalname_spellingofname_script text,
    geographicalname_spellingofname_script_nilreason text,
    geographicalname_spellingofname_script_nil boolean,
    geographicalname_spellingofname_transliterationscheme text,
    geographicalname_spellingofname_transliterationscheme_nilreason text,
    geographicalname_spellingofname_transliterationscheme_nil boolean
);
ALTER TABLE tnra.railwayyardnode_geographicalname_spelling OWNER TO elf_admin;

CREATE TABLE tnra.designspeed (
    gml_id text,
    identifier text,
    identifier_codespace text,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    speed numeric,
    speed_uom text,
    speedclass_owns boolean,
    speedclass_nilreason text,
    speedclass_remoteschema text,
    speedclass_fk text,
    speedclass_href text,
    CONSTRAINT designspeed_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnra.designspeed OWNER TO elf_admin;

CREATE TABLE tnra.designspeed_networkref (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.designspeed ON DELETE CASCADE,
    num integer not null,
    nilreason text,
    nil boolean,
    simplelinearreference_element_owns boolean,
    simplelinearreference_element_nilreason text,
    simplelinearreference_element_remoteschema text,
    simplelinearreference_element_fk text,
    simplelinearreference_element_href text,
    simplelinearreference_applicabledirection_owns boolean,
    simplelinearreference_applicabledirection_nilreason text,
    simplelinearreference_applicabledirection_remoteschema text,
    simplelinearreference_applicabledirection_nil boolean,
    simplelinearreference_applicabledirection_fk text,
    simplelinearreference_applicabledirection_href text,
    simplelinearreference_fromposition numeric,
    simplelinearreference_fromposition_uom text,
    simplelinearreference_toposition numeric,
    simplelinearreference_toposition_uom text,
    simplelinearreference_offset numeric,
    simplelinearreference_offset_nilreason text,
    simplelinearreference_offset_uom text,
    simplelinearreference_offset_nil boolean,
    simplepointreference_element_owns boolean,
    simplepointreference_element_nilreason text,
    simplepointreference_element_remoteschema text,
    simplepointreference_element_fk text,
    simplepointreference_element_href text,
    simplepointreference_applicabledirection_owns boolean,
    simplepointreference_applicabledirection_nilreason text,
    simplepointreference_applicabledirection_remoteschema text,
    simplepointreference_applicabledirection_nil boolean,
    simplepointreference_applicabledirection_fk text,
    simplepointreference_applicabledirection_href text,
    simplepointreference_atposition numeric,
    simplepointreference_atposition_uom text,
    simplepointreference_offset numeric,
    simplepointreference_offset_nilreason text,
    simplepointreference_offset_uom text,
    simplepointreference_offset_nil boolean,
    linkreference_element_owns boolean,
    linkreference_element_nilreason text,
    linkreference_element_remoteschema text,
    linkreference_element_fk text,
    linkreference_element_href text,
    linkreference_applicabledirection_owns boolean,
    linkreference_applicabledirection_nilreason text,
    linkreference_applicabledirection_remoteschema text,
    linkreference_applicabledirection_nil boolean,
    linkreference_applicabledirection_fk text,
    linkreference_applicabledirection_href text,
    networkreference_element_owns boolean,
    networkreference_element_nilreason text,
    networkreference_element_remoteschema text,
    networkreference_element_fk text,
    networkreference_element_href text
);
ALTER TABLE tnra.designspeed_networkref OWNER TO elf_admin;

CREATE TABLE tnra.railwayclass (
    gml_id text,
    identifier text,
    identifier_codespace text,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    railwayclass_owns boolean,
    railwayclass_nilreason text,
    railwayclass_remoteschema text,
    railwayclass_fk text,
    railwayclass_href text,
    CONSTRAINT railwayclass_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnra.railwayclass OWNER TO elf_admin;

CREATE TABLE tnra.railwayclass_networkref (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwayclass ON DELETE CASCADE,
    num integer not null,
    nilreason text,
    nil boolean,
    simplelinearreference_element_owns boolean,
    simplelinearreference_element_nilreason text,
    simplelinearreference_element_remoteschema text,
    simplelinearreference_element_fk text,
    simplelinearreference_element_href text,
    simplelinearreference_applicabledirection_owns boolean,
    simplelinearreference_applicabledirection_nilreason text,
    simplelinearreference_applicabledirection_remoteschema text,
    simplelinearreference_applicabledirection_nil boolean,
    simplelinearreference_applicabledirection_fk text,
    simplelinearreference_applicabledirection_href text,
    simplelinearreference_fromposition numeric,
    simplelinearreference_fromposition_uom text,
    simplelinearreference_toposition numeric,
    simplelinearreference_toposition_uom text,
    simplelinearreference_offset numeric,
    simplelinearreference_offset_nilreason text,
    simplelinearreference_offset_uom text,
    simplelinearreference_offset_nil boolean,
    simplepointreference_element_owns boolean,
    simplepointreference_element_nilreason text,
    simplepointreference_element_remoteschema text,
    simplepointreference_element_fk text,
    simplepointreference_element_href text,
    simplepointreference_applicabledirection_owns boolean,
    simplepointreference_applicabledirection_nilreason text,
    simplepointreference_applicabledirection_remoteschema text,
    simplepointreference_applicabledirection_nil boolean,
    simplepointreference_applicabledirection_fk text,
    simplepointreference_applicabledirection_href text,
    simplepointreference_atposition numeric,
    simplepointreference_atposition_uom text,
    simplepointreference_offset numeric,
    simplepointreference_offset_nilreason text,
    simplepointreference_offset_uom text,
    simplepointreference_offset_nil boolean,
    linkreference_element_owns boolean,
    linkreference_element_nilreason text,
    linkreference_element_remoteschema text,
    linkreference_element_fk text,
    linkreference_element_href text,
    linkreference_applicabledirection_owns boolean,
    linkreference_applicabledirection_nilreason text,
    linkreference_applicabledirection_remoteschema text,
    linkreference_applicabledirection_nil boolean,
    linkreference_applicabledirection_fk text,
    linkreference_applicabledirection_href text,
    networkreference_element_owns boolean,
    networkreference_element_nilreason text,
    networkreference_element_remoteschema text,
    networkreference_element_fk text,
    networkreference_element_href text
);
ALTER TABLE tnra.railwayclass_networkref OWNER TO elf_admin;

CREATE TABLE tnra.railwayelectrification (
    gml_id text,
    identifier text,
    identifier_codespace text,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    electrified boolean,
    railwaypowermethod_owns boolean,
    railwaypowermethod_nilreason text,
    railwaypowermethod_remoteschema text,
    railwaypowermethod_fk text,
    railwaypowermethod_href text,
    CONSTRAINT railwayelectrification_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnra.railwayelectrification OWNER TO elf_admin;

CREATE TABLE tnra.railwayelectrification_networkref (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwayelectrification ON DELETE CASCADE,
    num integer not null,
    nilreason text,
    nil boolean,
    simplelinearreference_element_owns boolean,
    simplelinearreference_element_nilreason text,
    simplelinearreference_element_remoteschema text,
    simplelinearreference_element_fk text,
    simplelinearreference_element_href text,
    simplelinearreference_applicabledirection_owns boolean,
    simplelinearreference_applicabledirection_nilreason text,
    simplelinearreference_applicabledirection_remoteschema text,
    simplelinearreference_applicabledirection_nil boolean,
    simplelinearreference_applicabledirection_fk text,
    simplelinearreference_applicabledirection_href text,
    simplelinearreference_fromposition numeric,
    simplelinearreference_fromposition_uom text,
    simplelinearreference_toposition numeric,
    simplelinearreference_toposition_uom text,
    simplelinearreference_offset numeric,
    simplelinearreference_offset_nilreason text,
    simplelinearreference_offset_uom text,
    simplelinearreference_offset_nil boolean,
    simplepointreference_element_owns boolean,
    simplepointreference_element_nilreason text,
    simplepointreference_element_remoteschema text,
    simplepointreference_element_fk text,
    simplepointreference_element_href text,
    simplepointreference_applicabledirection_owns boolean,
    simplepointreference_applicabledirection_nilreason text,
    simplepointreference_applicabledirection_remoteschema text,
    simplepointreference_applicabledirection_nil boolean,
    simplepointreference_applicabledirection_fk text,
    simplepointreference_applicabledirection_href text,
    simplepointreference_atposition numeric,
    simplepointreference_atposition_uom text,
    simplepointreference_offset numeric,
    simplepointreference_offset_nilreason text,
    simplepointreference_offset_uom text,
    simplepointreference_offset_nil boolean,
    linkreference_element_owns boolean,
    linkreference_element_nilreason text,
    linkreference_element_remoteschema text,
    linkreference_element_fk text,
    linkreference_element_href text,
    linkreference_applicabledirection_owns boolean,
    linkreference_applicabledirection_nilreason text,
    linkreference_applicabledirection_remoteschema text,
    linkreference_applicabledirection_nil boolean,
    linkreference_applicabledirection_fk text,
    linkreference_applicabledirection_href text,
    networkreference_element_owns boolean,
    networkreference_element_nilreason text,
    networkreference_element_remoteschema text,
    networkreference_element_fk text,
    networkreference_element_href text
);
ALTER TABLE tnra.railwayelectrification_networkref OWNER TO elf_admin;

CREATE TABLE tnra.railwaylink (
    gml_id text,
    identifier text,
    identifier_codespace text,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    centrelinegeometry_nilreason text,
    centrelinegeometry_remoteschema text,
    centrelinegeometry_owns boolean,
    fictitious boolean,
    endnode_owns boolean,
    endnode_nilreason text,
    endnode_remoteschema text,
    endnode_fk text,
    endnode_href text,
    startnode_owns boolean,
    startnode_nilreason text,
    startnode_remoteschema text,
    startnode_fk text,
    startnode_href text,
    geographicalname_nilreason text,
    geographicalname_nil boolean,
    geographicalname_language text,
    geographicalname_language_nilreason text,
    geographicalname_language_nil boolean,
    geographicalname_nativeness_owns boolean,
    geographicalname_nativeness_nilreason text,
    geographicalname_nativeness_remoteschema text,
    geographicalname_nativeness_nil boolean,
    geographicalname_nativeness_fk text,
    geographicalname_nativeness_href text,
    geographicalname_namestatus_owns boolean,
    geographicalname_namestatus_nilreason text,
    geographicalname_namestatus_remoteschema text,
    geographicalname_namestatus_nil boolean,
    geographicalname_namestatus_fk text,
    geographicalname_namestatus_href text,
    geographicalname_sourceofname text,
    geographicalname_sourceofname_nilreason text,
    geographicalname_sourceofname_nil boolean,
    geographicalname_pronunciation_nilreason text,
    geographicalname_pronunciation_nil boolean,
    geographicalname_pronunciationofname_soundlink text,
    geographicalname_pronunciationofname_soundlink_nilreason text,
    geographicalname_pronunciationofname_soundlink_nil boolean,
    geographicalname_pronunciationofname_pronunciationipa text,
    geographicalname_pronunciationofname_pronunciationipa_nilreason text,
    geographicalname_pronunciationofname_pronunciationipa_nil boolean,
    geographicalname_grammaticalgender_owns boolean,
    geographicalname_grammaticalgender_nilreason text,
    geographicalname_grammaticalgender_remoteschema text,
    geographicalname_grammaticalgender_nil boolean,
    geographicalname_grammaticalgender_fk text,
    geographicalname_grammaticalgender_href text,
    geographicalname_grammaticalnumber_owns boolean,
    geographicalname_grammaticalnumber_nilreason text,
    geographicalname_grammaticalnumber_remoteschema text,
    geographicalname_grammaticalnumber_nil boolean,
    geographicalname_grammaticalnumber_fk text,
    geographicalname_grammaticalnumber_href text,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    transeuropeantransportnetwork boolean,
    CONSTRAINT railwaylink_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnra.railwaylink OWNER TO elf_admin;

CREATE TABLE tnra.railwaylink_innetwork (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwaylink ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnra.railwaylink_innetwork OWNER TO elf_admin;

SELECT ADDGEOMETRYCOLUMN('tnra', 'railwaylink','centrelinegeometry_value','4258','GEOMETRY', 2);
CREATE INDEX railwaylink_geometry_idx ON tnra.railwaylink USING GIST (centrelinegeometry_value);

CREATE TABLE tnra.railwaylink_geographicalname_spelling (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwaylink ON DELETE CASCADE,
    num integer not null,
    geographicalname_spellingofname_text text,
    geographicalname_spellingofname_script text,
    geographicalname_spellingofname_script_nilreason text,
    geographicalname_spellingofname_script_nil boolean,
    geographicalname_spellingofname_transliterationscheme text,
    geographicalname_spellingofname_transliterationscheme_nilreason text,
    geographicalname_spellingofname_transliterationscheme_nil boolean
);
ALTER TABLE tnra.railwaylink_geographicalname_spelling OWNER TO elf_admin;

CREATE TABLE tnra.railwaystationnode (
    gml_id text,
    identifier text,
    identifier_codespace text,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    geometry_nilreason text,
    geometry_remoteschema text,
    geometry_owns boolean,
    geographicalname_nilreason text,
    geographicalname_nil boolean,
    geographicalname_language text,
    geographicalname_language_nilreason text,
    geographicalname_language_nil boolean,
    geographicalname_nativeness_owns boolean,
    geographicalname_nativeness_nilreason text,
    geographicalname_nativeness_remoteschema text,
    geographicalname_nativeness_nil boolean,
    geographicalname_nativeness_fk text,
    geographicalname_nativeness_href text,
    geographicalname_namestatus_owns boolean,
    geographicalname_namestatus_nilreason text,
    geographicalname_namestatus_remoteschema text,
    geographicalname_namestatus_nil boolean,
    geographicalname_namestatus_fk text,
    geographicalname_namestatus_href text,
    geographicalname_sourceofname text,
    geographicalname_sourceofname_nilreason text,
    geographicalname_sourceofname_nil boolean,
    geographicalname_pronunciation_nilreason text,
    geographicalname_pronunciation_nil boolean,
    geographicalname_pronunciationofname_soundlink text,
    geographicalname_pronunciationofname_soundlink_nilreason text,
    geographicalname_pronunciationofname_soundlink_nil boolean,
    geographicalname_pronunciationofname_pronunciationipa text,
    geographicalname_pronunciationofname_pronunciationipa_nilreason text,
    geographicalname_pronunciationofname_pronunciationipa_nil boolean,
    geographicalname_grammaticalgender_owns boolean,
    geographicalname_grammaticalgender_nilreason text,
    geographicalname_grammaticalgender_remoteschema text,
    geographicalname_grammaticalgender_nil boolean,
    geographicalname_grammaticalgender_fk text,
    geographicalname_grammaticalgender_href text,
    geographicalname_grammaticalnumber_owns boolean,
    geographicalname_grammaticalnumber_nilreason text,
    geographicalname_grammaticalnumber_remoteschema text,
    geographicalname_grammaticalnumber_nil boolean,
    geographicalname_grammaticalnumber_fk text,
    geographicalname_grammaticalnumber_href text,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    formofnode_owns boolean,
    formofnode_nilreason text,
    formofnode_remoteschema text,
    formofnode_nil boolean,
    formofnode_fk text,
    formofnode_href text,
    numberofplatforms integer,
    numberofplatforms_nilreason text,
    numberofplatforms_nil boolean,
    facilitytype_owns boolean,
    facilitytype_nilreason text,
    facilitytype_remoteschema text,
    facilitytype_fk text,
    facilitytype_href text,
    CONSTRAINT railwaystationnode_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnra.railwaystationnode OWNER TO elf_admin;

CREATE TABLE tnra.railwaystationnode_innetwork (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwaystationnode ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnra.railwaystationnode_innetwork OWNER TO elf_admin;

SELECT ADDGEOMETRYCOLUMN('tnra', 'railwaystationnode','geometry_value','4258','GEOMETRY', 2);
CREATE INDEX railwaystationnode_geometry_idx ON tnra.railwaystationnode USING GIST (geometry_value);

CREATE TABLE tnra.railwaystationnode_spokeend (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwaystationnode ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnra.railwaystationnode_spokeend OWNER TO elf_admin;

CREATE TABLE tnra.railwaystationnode_spokestart (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwaystationnode ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnra.railwaystationnode_spokestart OWNER TO elf_admin;

CREATE TABLE tnra.railwaystationnode_geographicalname_spelling (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnra.railwaystationnode ON DELETE CASCADE,
    num integer not null,
    geographicalname_spellingofname_text text,
    geographicalname_spellingofname_script text,
    geographicalname_spellingofname_script_nilreason text,
    geographicalname_spellingofname_script_nil boolean,
    geographicalname_spellingofname_transliterationscheme text,
    geographicalname_spellingofname_transliterationscheme_nilreason text,
    geographicalname_spellingofname_transliterationscheme_nil boolean
);
ALTER TABLE tnra.railwaystationnode_geographicalname_spelling OWNER TO elf_admin;

