-- Schema: tnro

-- DROP SCHEMA tnro;

CREATE SCHEMA tnro
  AUTHORIZATION elf_admin;

COMMENT ON SCHEMA tnro
  IS 'Schemata für TransprotNetwork Roads';
  
-- == Tabellen =====

-- == ERoad ================================  
CREATE TABLE tnro.eroad (
    gml_id text,
    identifier text,
    identifier_codespace text,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    geographicalname_nilreason text,
    geographicalname_nil boolean,
    geographicalname_language text,
    geographicalname_language_nilreason text,
    geographicalname_language_nil boolean,
    geographicalname_nativeness_owns boolean,
    geographicalname_nativeness_nilreason text,
    geographicalname_nativeness_remoteschema text,
    geographicalname_nativeness_nil boolean,
    geographicalname_nativeness_fk text,
    geographicalname_nativeness_href text,
    geographicalname_namestatus_owns boolean,
    geographicalname_namestatus_nilreason text,
    geographicalname_namestatus_remoteschema text,
    geographicalname_namestatus_nil boolean,
    geographicalname_namestatus_fk text,
    geographicalname_namestatus_href text,
    geographicalname_sourceofname text,
    geographicalname_sourceofname_nilreason text,
    geographicalname_sourceofname_nil boolean,
    geographicalname_pronunciation_nilreason text,
    geographicalname_pronunciation_nil boolean,
    geographicalname_pronunciation_soundlink text,
    geographicalname_pronunciation_soundlink_nilreason text,
    geographicalname_pronunciation_soundlink_nil boolean,
    geographicalname_pronunciation_ipa text,
    geographicalname_pronunciation_ipa_nilreason text,
    geographicalname_pronunciation_ipa_nil boolean,
    geographicalname_grammaticalgender_owns boolean,
    geographicalname_grammaticalgender_nilreason text,
    geographicalname_grammaticalgender_remoteschema text,
    geographicalname_grammaticalgender_nil boolean,
    geographicalname_grammaticalgender_fk text,
    geographicalname_grammaticalgender_href text,
    geographicalname_grammaticalnumber_owns boolean,
    geographicalname_grammaticalnumber_nilreason text,
    geographicalname_grammaticalnumber_remoteschema text,
    geographicalname_grammaticalnumber_nil boolean,
    geographicalname_grammaticalnumber_fk text,
    geographicalname_grammaticalnumber_href text,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    europeanroutenumber text,
    europeanroutenumber_nilreason text,
    europeanroutenumber_nil boolean,
    CONSTRAINT eroad_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnro.eroad OWNER TO elf_admin;

CREATE TABLE tnro.eroad_innetwork (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.eroad ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnro.eroad_innetwork OWNER TO elf_admin;

CREATE TABLE tnro.eroad_link (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.eroad ON DELETE CASCADE,
    num integer not null,
    nilreason text,
    remoteschema text,
    owns boolean,
    fk text,
    href text
);
ALTER TABLE tnro.eroad_link OWNER TO elf_admin;

CREATE TABLE tnro.eroad_geographicalname_spelling (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.eroad ON DELETE CASCADE,
    num integer not null,
    geographicalname_spellingofname_text text,
    geographicalname_spellingofname_script text,
    geographicalname_spellingofname_script_nilreason text,
    geographicalname_spellingofname_script_nil boolean,
    geographicalname_spellingofname_transliterationscheme text,
    geographicalname_spellingofname_transliterationscheme_nilreason text,
    geographicalname_spellingofname_transliterationscheme_nil boolean
);
ALTER TABLE tnro.eroad_geographicalname_spelling OWNER TO elf_admin;

CREATE TABLE tnro.eroad_post (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.eroad ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnro.eroad_post OWNER TO elf_admin;

CREATE TABLE tnro.formofway (
    gml_id text,
    identifier text,
    identifier_codespace text,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    formofway_owns boolean,
    formofway_nilreason text,
    formofway_remoteschema text,
    formofway_fk text,
    formofway_href text,
    CONSTRAINT formofway_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnro.formofway OWNER TO elf_admin;

CREATE TABLE tnro.formofway_networkref (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.formofway ON DELETE CASCADE,
    num integer not null,
    nilreason text,
    nil boolean,
    simplelinearreference_element_owns boolean,
    simplelinearreference_element_nilreason text,
    simplelinearreference_element_remoteschema text,
    simplelinearreference_element_fk text,
    simplelinearreference_element_href text,
    simplelinearreference_applicabledirection_owns boolean,
    simplelinearreference_applicabledirection_nilreason text,
    simplelinearreference_applicabledirection_remoteschema text,
    simplelinearreference_applicabledirection_nil boolean,
    simplelinearreference_applicabledirection_fk text,
    simplelinearreference_applicabledirection_href text,
    simplelinearreference_fromposition numeric,
    simplelinearreference_fromposition_uom text,
    simplelinearreference_toposition numeric,
    simplelinearreference_toposition_uom text,
    simplelinearreference_offset numeric,
    simplelinearreference_offset_nilreason text,
    simplelinearreference_offset_uom text,
    simplelinearreference_offset_nil boolean,
    simplepointreference_element_owns boolean,
    simplepointreference_element_nilreason text,
    simplepointreference_element_remoteschema text,
    simplepointreference_element_fk text,
    simplepointreference_element_href text,
    simplepointreference_applicabledirection_owns boolean,
    simplepointreference_applicabledirection_nilreason text,
    simplepointreference_applicabledirection_remoteschema text,
    simplepointreference_applicabledirection_nil boolean,
    simplepointreference_applicabledirection_fk text,
    simplepointreference_applicabledirection_href text,
    simplepointreference_atposition numeric,
    simplepointreference_atposition_uom text,
    simplepointreference_offset numeric,
    simplepointreference_offset_nilreason text,
    simplepointreference_offset_uom text,
    simplepointreference_offset_nil boolean,
    linkreference_element_owns boolean,
    linkreference_element_nilreason text,
    linkreference_element_remoteschema text,
    linkreference_element_fk text,
    linkreference_element_href text,
    linkreference_applicabledirection_owns boolean,
    linkreference_applicabledirection_nilreason text,
    linkreference_applicabledirection_remoteschema text,
    linkreference_applicabledirection_nil boolean,
    linkreference_applicabledirection_fk text,
    linkreference_applicabledirection_href text,
    networkreference_element_owns boolean,
    networkreference_element_nilreason text,
    networkreference_element_remoteschema text,
    networkreference_element_fk text,
    networkreference_element_href text
);
ALTER TABLE tnro.formofway_networkref OWNER TO elf_admin;

CREATE TABLE tnro.functionalroadclass (
    gml_id text,
    identifier text,
    identifier_codespace text,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    functionalclass text,
    CONSTRAINT functionalroadclass_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnro.functionalroadclass OWNER TO elf_admin;

CREATE TABLE tnro.functionalroadclass_networkref (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.functionalroadclass ON DELETE CASCADE,
    num integer not null,
    nilreason text,
    nil boolean,
    simplelinearreference_element_owns boolean,
    simplelinearreference_element_nilreason text,
    simplelinearreference_element_remoteschema text,
    simplelinearreference_element_fk text,
    simplelinearreference_element_href text,
    simplelinearreference_applicabledirection_owns boolean,
    simplelinearreference_applicabledirection_nilreason text,
    simplelinearreference_applicabledirection_remoteschema text,
    simplelinearreference_applicabledirection_nil boolean,
    simplelinearreference_applicabledirection_fk text,
    simplelinearreference_applicabledirection_href text,
    simplelinearreference_fromposition numeric,
    simplelinearreference_fromposition_uom text,
    simplelinearreference_toposition numeric,
    simplelinearreference_toposition_uom text,
    simplelinearreference_offset numeric,
    simplelinearreference_offset_nilreason text,
    simplelinearreference_offset_uom text,
    simplelinearreference_offset_nil boolean,
    simplepointreference_element_owns boolean,
    simplepointreference_element_nilreason text,
    simplepointreference_element_remoteschema text,
    simplepointreference_element_fk text,
    simplepointreference_element_href text,
    simplepointreference_applicabledirection_owns boolean,
    simplepointreference_applicabledirection_nilreason text,
    simplepointreference_applicabledirection_remoteschema text,
    simplepointreference_applicabledirection_nil boolean,
    simplepointreference_applicabledirection_fk text,
    simplepointreference_applicabledirection_href text,
    simplepointreference_atposition numeric,
    simplepointreference_atposition_uom text,
    simplepointreference_offset numeric,
    simplepointreference_offset_nilreason text,
    simplepointreference_offset_uom text,
    simplepointreference_offset_nil boolean,
    linkreference_element_owns boolean,
    linkreference_element_nilreason text,
    linkreference_element_remoteschema text,
    linkreference_element_fk text,
    linkreference_element_href text,
    linkreference_applicabledirection_owns boolean,
    linkreference_applicabledirection_nilreason text,
    linkreference_applicabledirection_remoteschema text,
    linkreference_applicabledirection_nil boolean,
    linkreference_applicabledirection_fk text,
    linkreference_applicabledirection_href text,
    networkreference_element_owns boolean,
    networkreference_element_nilreason text,
    networkreference_element_remoteschema text,
    networkreference_element_fk text,
    networkreference_element_href text
);
ALTER TABLE tnro.functionalroadclass_networkref OWNER TO elf_admin;

CREATE TABLE tnro.numberoflanes (
    gml_id text,
    identifier text,
    identifier_codespace text,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    direction_owns boolean,
    direction_nilreason text,
    direction_remoteschema text,
    direction_nil boolean,
    direction_fk text,
    direction_href text,
    minmaxnumberoflanes text,
    minmaxnumberoflanes_nilreason text,
    minmaxnumberoflanes_nil boolean,
    numberoflanes integer,
    CONSTRAINT numberoflanes_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnro.numberoflanes OWNER TO elf_admin;

CREATE TABLE tnro.numberoflanes_networkref (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.numberoflanes ON DELETE CASCADE,
    num integer not null,
    nilreason text,
    nil boolean,
    simplelinearreference_element_owns boolean,
    simplelinearreference_element_nilreason text,
    simplelinearreference_element_remoteschema text,
    simplelinearreference_element_fk text,
    simplelinearreference_element_href text,
    simplelinearreference_applicabledirection_owns boolean,
    simplelinearreference_applicabledirection_nilreason text,
    simplelinearreference_applicabledirection_remoteschema text,
    simplelinearreference_applicabledirection_nil boolean,
    simplelinearreference_applicabledirection_fk text,
    simplelinearreference_applicabledirection_href text,
    simplelinearreference_fromposition numeric,
    simplelinearreference_fromposition_uom text,
    simplelinearreference_toposition numeric,
    simplelinearreference_toposition_uom text,
    simplelinearreference_offset numeric,
    simplelinearreference_offset_nilreason text,
    simplelinearreference_offset_uom text,
    simplelinearreference_offset_nil boolean,
    simplepointreference_element_owns boolean,
    simplepointreference_element_nilreason text,
    simplepointreference_element_remoteschema text,
    simplepointreference_element_fk text,
    simplepointreference_element_href text,
    simplepointreference_applicabledirection_owns boolean,
    simplepointreference_applicabledirection_nilreason text,
    simplepointreference_applicabledirection_remoteschema text,
    simplepointreference_applicabledirection_nil boolean,
    simplepointreference_applicabledirection_fk text,
    simplepointreference_applicabledirection_href text,
    simplepointreference_atposition numeric,
    simplepointreference_atposition_uom text,
    simplepointreference_offset numeric,
    simplepointreference_offset_nilreason text,
    simplepointreference_offset_uom text,
    simplepointreference_offset_nil boolean,
    linkreference_element_owns boolean,
    linkreference_element_nilreason text,
    linkreference_element_remoteschema text,
    linkreference_element_fk text,
    linkreference_element_href text,
    linkreference_applicabledirection_owns boolean,
    linkreference_applicabledirection_nilreason text,
    linkreference_applicabledirection_remoteschema text,
    linkreference_applicabledirection_nil boolean,
    linkreference_applicabledirection_fk text,
    linkreference_applicabledirection_href text,
    networkreference_element_owns boolean,
    networkreference_element_nilreason text,
    networkreference_element_remoteschema text,
    networkreference_element_fk text,
    networkreference_element_href text
);
ALTER TABLE tnro.numberoflanes_networkref OWNER TO elf_admin;

CREATE TABLE tnro.road (
    gml_id text,
    identifier text,
    identifier_codespace text,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    geographicalname_nilreason text,
    geographicalname_nil boolean,
    geographicalname_language text,
    geographicalname_language_nilreason text,
    geographicalname_language_nil boolean,
    geographicalname_nativeness_owns boolean,
    geographicalname_nativeness_nilreason text,
    geographicalname_nativeness_remoteschema text,
    geographicalname_nativeness_nil boolean,
    geographicalname_nativeness_fk text,
    geographicalname_nativeness_href text,
    geographicalname_namestatus_owns boolean,
    geographicalname_namestatus_nilreason text,
    geographicalname_namestatus_remoteschema text,
    geographicalname_namestatus_nil boolean,
    geographicalname_namestatus_fk text,
    geographicalname_namestatus_href text,
    geographicalname_sourceofname text,
    geographicalname_sourceofname_nilreason text,
    geographicalname_sourceofname_nil boolean,
    geographicalname_pronunciation_nilreason text,
    geographicalname_pronunciation_nil boolean,
    geographicalname_pronunciation_soundlink text,
    geographicalname_pronunciation_soundlink_nilreason text,
    geographicalname_pronunciation_soundlink_nil boolean,
    geographicalname_pronunciation_ipa text,
    geographicalname_pronunciation_ipa_nilreason text,
    geographicalname_pronunciation_ipa_nil boolean,
    geographicalname_grammaticalgender_owns boolean,
    geographicalname_grammaticalgender_nilreason text,
    geographicalname_grammaticalgender_remoteschema text,
    geographicalname_grammaticalgender_nil boolean,
    geographicalname_grammaticalgender_fk text,
    geographicalname_grammaticalgender_href text,
    geographicalname_grammaticalnumber_owns boolean,
    geographicalname_grammaticalnumber_nilreason text,
    geographicalname_grammaticalnumber_remoteschema text,
    geographicalname_grammaticalnumber_nil boolean,
    geographicalname_grammaticalnumber_fk text,
    geographicalname_grammaticalnumber_href text,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    localroadcode text,
    localroadcode_nilreason text,
    localroadcode_nil boolean,
    nationalroadcode text,
    nationalroadcode_nilreason text,
    nationalroadcode_nil boolean,
    CONSTRAINT road_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnro.road OWNER TO elf_admin;

CREATE TABLE tnro.road_innetwork (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.road ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnro.road_innetwork OWNER TO elf_admin;

CREATE TABLE tnro.road_link (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.road ON DELETE CASCADE,
    num integer not null,
    nilreason text,
    remoteschema text,
    owns boolean,
    fk text,
    href text
);
ALTER TABLE tnro.road_link OWNER TO elf_admin;

CREATE TABLE tnro.road_geographicalname_spelling (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.road ON DELETE CASCADE,
    num integer not null,
    geographicalname_spellingofname_text text,
    geographicalname_spellingofname_script text,
    geographicalname_spellingofname_script_nilreason text,
    geographicalname_spellingofname_script_nil boolean,
    geographicalname_spellingofname_transliterationscheme text,
    geographicalname_spellingofname_transliterationscheme_nilreason text,
    geographicalname_spellingofname_transliterationscheme_nil boolean
);
ALTER TABLE tnro.road_geographicalname_spelling OWNER TO elf_admin;

CREATE TABLE tnro.road_post (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.road ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnro.road_post OWNER TO elf_admin;

CREATE TABLE tnro.roadarea (
    gml_id text,
    identifier text,
    identifier_codespace text,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    geometry_nilreason text,
    geometry_remoteschema text,
    geometry_owns boolean,
    geographicalname_nilreason text,
    geographicalname_nil boolean,
    geographicalname_language text,
    geographicalname_language_nilreason text,
    geographicalname_language_nil boolean,
    geographicalname_nativeness_owns boolean,
    geographicalname_nativeness_nilreason text,
    geographicalname_nativeness_remoteschema text,
    geographicalname_nativeness_nil boolean,
    geographicalname_nativeness_fk text,
    geographicalname_nativeness_href text,
    geographicalname_namestatus_owns boolean,
    geographicalname_namestatus_nilreason text,
    geographicalname_namestatus_remoteschema text,
    geographicalname_namestatus_nil boolean,
    geographicalname_namestatus_fk text,
    geographicalname_namestatus_href text,
    geographicalname_sourceofname text,
    geographicalname_sourceofname_nilreason text,
    geographicalname_sourceofname_nil boolean,
    geographicalname_pronunciation_nilreason text,
    geographicalname_pronunciation_nil boolean,
    geographicalname_pronunciation_soundlink text,
    geographicalname_pronunciation_soundlink_nilreason text,
    geographicalname_pronunciation_soundlink_nil boolean,
    geographicalname_pronunciation_ipa text,
    geographicalname_pronunciation_ipa_nilreason text,
    geographicalname_pronunciation_ipa_nil boolean,
    geographicalname_grammaticalgender_owns boolean,
    geographicalname_grammaticalgender_nilreason text,
    geographicalname_grammaticalgender_remoteschema text,
    geographicalname_grammaticalgender_nil boolean,
    geographicalname_grammaticalgender_fk text,
    geographicalname_grammaticalgender_href text,
    geographicalname_grammaticalnumber_owns boolean,
    geographicalname_grammaticalnumber_nilreason text,
    geographicalname_grammaticalnumber_remoteschema text,
    geographicalname_grammaticalnumber_nil boolean,
    geographicalname_grammaticalnumber_fk text,
    geographicalname_grammaticalnumber_href text,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    CONSTRAINT roadarea_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnro.roadarea OWNER TO elf_admin;

CREATE TABLE tnro.roadarea_innetwork (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.roadarea ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnro.roadarea_innetwork OWNER TO elf_admin;

SELECT ADDGEOMETRYCOLUMN('tnro', 'roadarea','geometry_value','4258','GEOMETRY', 2);
CREATE INDEX roadarea_geometry_idx ON tnro.roadarea USING GIST (geometry_value);

CREATE TABLE tnro.roadarea_geographicalname_spelling (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.roadarea ON DELETE CASCADE,
    num integer not null,
    geographicalname_spellingofname_text text,
    geographicalname_spellingofname_script text,
    geographicalname_spellingofname_script_nilreason text,
    geographicalname_spellingofname_script_nil boolean,
    geographicalname_spellingofname_transliterationscheme text,
    geographicalname_spellingofname_transliterationscheme_nilreason text,
    geographicalname_spellingofname_transliterationscheme_nil boolean
);
ALTER TABLE tnro.roadarea_geographicalname_spelling OWNER TO elf_admin;

CREATE TABLE tnro.roadlinksequence (
    gml_id text,
    identifier text,
    identifier_codespace text,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    geographicalname_nilreason text,
    geographicalname_nil boolean,
    geographicalname_language text,
    geographicalname_language_nilreason text,
    geographicalname_language_nil boolean,
    geographicalname_nativeness_owns boolean,
    geographicalname_nativeness_nilreason text,
    geographicalname_nativeness_remoteschema text,
    geographicalname_nativeness_nil boolean,
    geographicalname_nativeness_fk text,
    geographicalname_nativeness_href text,
    geographicalname_namestatus_owns boolean,
    geographicalname_namestatus_nilreason text,
    geographicalname_namestatus_remoteschema text,
    geographicalname_namestatus_nil boolean,
    geographicalname_namestatus_fk text,
    geographicalname_namestatus_href text,
    geographicalname_sourceofname text,
    geographicalname_sourceofname_nilreason text,
    geographicalname_sourceofname_nil boolean,
    geographicalname_pronunciation_nilreason text,
    geographicalname_pronunciation_nil boolean,
    geographicalname_pronunciation_soundlink text,
    geographicalname_pronunciation_soundlink_nilreason text,
    geographicalname_pronunciation_soundlink_nil boolean,
    geographicalname_pronunciation_ipa text,
    geographicalname_pronunciation_ipa_nilreason text,
    geographicalname_pronunciation_ipa_nil boolean,
    geographicalname_grammaticalgender_owns boolean,
    geographicalname_grammaticalgender_nilreason text,
    geographicalname_grammaticalgender_remoteschema text,
    geographicalname_grammaticalgender_nil boolean,
    geographicalname_grammaticalgender_fk text,
    geographicalname_grammaticalgender_href text,
    geographicalname_grammaticalnumber_owns boolean,
    geographicalname_grammaticalnumber_nilreason text,
    geographicalname_grammaticalnumber_remoteschema text,
    geographicalname_grammaticalnumber_nil boolean,
    geographicalname_grammaticalnumber_fk text,
    geographicalname_grammaticalnumber_href text,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    CONSTRAINT roadlinksequence_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnro.roadlinksequence OWNER TO elf_admin;

CREATE TABLE tnro.roadlinksequence_innetwork (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.roadlinksequence ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnro.roadlinksequence_innetwork OWNER TO elf_admin;

CREATE TABLE tnro.roadlinksequence_link (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.roadlinksequence ON DELETE CASCADE,
    num integer not null,
    directedlink_direction text,
    directedlink_link_owns boolean,
    directedlink_link_nilreason text,
    directedlink_link_remoteschema text,
    directedlink_link_fk text,
    directedlink_link_href text
);
ALTER TABLE tnro.roadlinksequence_link OWNER TO elf_admin;

CREATE TABLE tnro.roadlinksequence_geographicalname_spelling (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.roadlinksequence ON DELETE CASCADE,
    num integer not null,
    geographicalname_spellingofname_text text,
    geographicalname_spellingofname_script text,
    geographicalname_spellingofname_script_nilreason text,
    geographicalname_spellingofname_script_nil boolean,
    geographicalname_spellingofname_transliterationscheme text,
    geographicalname_spellingofname_transliterationscheme_nilreason text,
    geographicalname_spellingofname_transliterationscheme_nil boolean
);
ALTER TABLE tnro.roadlinksequence_geographicalname_spelling OWNER TO elf_admin;

CREATE TABLE tnro.roadname (
    gml_id text,
    identifier text,
    identifier_codespace text,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    name_geographicalname_language text,
    name_geographicalname_language_nilreason text,
    name_geographicalname_language_nil boolean,
    name_geographicalname_nativeness_owns boolean,
    name_geographicalname_nativeness_nilreason text,
    name_geographicalname_nativeness_remoteschema text,
    name_geographicalname_nativeness_nil boolean,
    name_geographicalname_nativeness_fk text,
    name_geographicalname_nativeness_href text,
    name_geographicalname_namestatus_owns boolean,
    name_geographicalname_namestatus_nilreason text,
    name_geographicalname_namestatus_remoteschema text,
    name_geographicalname_namestatus_nil boolean,
    name_geographicalname_namestatus_fk text,
    name_geographicalname_namestatus_href text,
    name_geographicalname_sourceofname text,
    name_geographicalname_sourceofname_nilreason text,
    name_geographicalname_sourceofname_nil boolean,
    name_geographicalname_pronunciation_nilreason text,
    name_geographicalname_pronunciation_nil boolean,
    name_geographicalname_pronunciation_soundlink text,
    name_geographicalname_pronunciation_soundlink_nilreason text,
    name_geographicalname_pronunciation_soundlink_nil boolean,
    name_geographicalname_pronunciation_ipa text,
    name_geographicalname_pronunciation_ipa_nilreason text,
    name_geographicalname_pronunciation_ipa_nil boolean,
    name_geographicalname_grammaticalgender_owns boolean,
    name_geographicalname_grammaticalgender_nilreason text,
    name_geographicalname_grammaticalgender_remoteschema text,
    name_geographicalname_grammaticalgender_nil boolean,
    name_geographicalname_grammaticalgender_fk text,
    name_geographicalname_grammaticalgender_href text,
    name_geographicalname_grammaticalnumber_owns boolean,
    name_geographicalname_grammaticalnumber_nilreason text,
    name_geographicalname_grammaticalnumber_remoteschema text,
    name_geographicalname_grammaticalnumber_nil boolean,
    name_geographicalname_grammaticalnumber_fk text,
    name_geographicalname_grammaticalnumber_href text,
    CONSTRAINT roadname_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnro.roadname OWNER TO elf_admin;

CREATE TABLE tnro.roadname_networkref (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.roadname ON DELETE CASCADE,
    num integer not null,
    nilreason text,
    nil boolean,
    simplelinearreference_element_owns boolean,
    simplelinearreference_element_nilreason text,
    simplelinearreference_element_remoteschema text,
    simplelinearreference_element_fk text,
    simplelinearreference_element_href text,
    simplelinearreference_applicabledirection_owns boolean,
    simplelinearreference_applicabledirection_nilreason text,
    simplelinearreference_applicabledirection_remoteschema text,
    simplelinearreference_applicabledirection_nil boolean,
    simplelinearreference_applicabledirection_fk text,
    simplelinearreference_applicabledirection_href text,
    simplelinearreference_fromposition numeric,
    simplelinearreference_fromposition_uom text,
    simplelinearreference_toposition numeric,
    simplelinearreference_toposition_uom text,
    simplelinearreference_offset numeric,
    simplelinearreference_offset_nilreason text,
    simplelinearreference_offset_uom text,
    simplelinearreference_offset_nil boolean,
    simplepointreference_element_owns boolean,
    simplepointreference_element_nilreason text,
    simplepointreference_element_remoteschema text,
    simplepointreference_element_fk text,
    simplepointreference_element_href text,
    simplepointreference_applicabledirection_owns boolean,
    simplepointreference_applicabledirection_nilreason text,
    simplepointreference_applicabledirection_remoteschema text,
    simplepointreference_applicabledirection_nil boolean,
    simplepointreference_applicabledirection_fk text,
    simplepointreference_applicabledirection_href text,
    simplepointreference_atposition numeric,
    simplepointreference_atposition_uom text,
    simplepointreference_offset numeric,
    simplepointreference_offset_nilreason text,
    simplepointreference_offset_uom text,
    simplepointreference_offset_nil boolean,
    linkreference_element_owns boolean,
    linkreference_element_nilreason text,
    linkreference_element_remoteschema text,
    linkreference_element_fk text,
    linkreference_element_href text,
    linkreference_applicabledirection_owns boolean,
    linkreference_applicabledirection_nilreason text,
    linkreference_applicabledirection_remoteschema text,
    linkreference_applicabledirection_nil boolean,
    linkreference_applicabledirection_fk text,
    linkreference_applicabledirection_href text,
    networkreference_element_owns boolean,
    networkreference_element_nilreason text,
    networkreference_element_remoteschema text,
    networkreference_element_fk text,
    networkreference_element_href text
);
ALTER TABLE tnro.roadname_networkref OWNER TO elf_admin;

CREATE TABLE tnro.roadname_name_geographicalname_spelling (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.roadname ON DELETE CASCADE,
    num integer not null,
    name_geographicalname_spellingofname_text text,
    name_geographicalname_spellingofname_script text,
    name_geographicalname_spellingofname_script_nilreason text,
    name_geographicalname_spellingofname_script_nil boolean,
    name_geographicalname_spellingofname_transliterationscheme text,
    name_geographicalname_spellingofname_transliterationscheme_nilreason text,
    name_geographicalname_spellingofname_transliterationscheme_nil boolean
);
ALTER TABLE tnro.roadname_name_geographicalname_spelling OWNER TO elf_admin;

CREATE TABLE tnro.roadnode (
    gml_id text,
    identifier text,
    identifier_codespace text,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    geometry_nilreason text,
    geometry_remoteschema text,
    geometry_owns boolean,
    geographicalname_nilreason text,
    geographicalname_nil boolean,
    geographicalname_language text,
    geographicalname_language_nilreason text,
    geographicalname_language_nil boolean,
    geographicalname_nativeness_owns boolean,
    geographicalname_nativeness_nilreason text,
    geographicalname_nativeness_remoteschema text,
    geographicalname_nativeness_nil boolean,
    geographicalname_nativeness_fk text,
    geographicalname_nativeness_href text,
    geographicalname_namestatus_owns boolean,
    geographicalname_namestatus_nilreason text,
    geographicalname_namestatus_remoteschema text,
    geographicalname_namestatus_nil boolean,
    geographicalname_namestatus_fk text,
    geographicalname_namestatus_href text,
    geographicalname_sourceofname text,
    geographicalname_sourceofname_nilreason text,
    geographicalname_sourceofname_nil boolean,
    geographicalname_pronunciation_nilreason text,
    geographicalname_pronunciation_nil boolean,
    geographicalname_pronunciation_soundlink text,
    geographicalname_pronunciation_soundlink_nilreason text,
    geographicalname_pronunciation_soundlink_nil boolean,
    geographicalname_pronunciation_ipa text,
    geographicalname_pronunciation_ipa_nilreason text,
    geographicalname_pronunciation_ipa_nil boolean,
    geographicalname_grammaticalgender_owns boolean,
    geographicalname_grammaticalgender_nilreason text,
    geographicalname_grammaticalgender_remoteschema text,
    geographicalname_grammaticalgender_nil boolean,
    geographicalname_grammaticalgender_fk text,
    geographicalname_grammaticalgender_href text,
    geographicalname_grammaticalnumber_owns boolean,
    geographicalname_grammaticalnumber_nilreason text,
    geographicalname_grammaticalnumber_remoteschema text,
    geographicalname_grammaticalnumber_nil boolean,
    geographicalname_grammaticalnumber_fk text,
    geographicalname_grammaticalnumber_href text,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    formofroadnode_owns boolean,
    formofroadnode_nilreason text,
    formofroadnode_remoteschema text,
    formofroadnode_nil boolean,
    formofroadnode_fk text,
    formofroadnode_href text,
    CONSTRAINT roadnode_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnro.roadnode OWNER TO elf_admin;

CREATE TABLE tnro.roadnode_innetwork (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.roadnode ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnro.roadnode_innetwork OWNER TO elf_admin;

SELECT ADDGEOMETRYCOLUMN('tnro', 'roadnode','geometry_value','4258','GEOMETRY', 2);
CREATE INDEX roadnode_geometry_idx ON tnro.roadnode USING GIST (geometry_value);

CREATE TABLE tnro.roadnode_spokeend (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.roadnode ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnro.roadnode_spokeend OWNER TO elf_admin;

CREATE TABLE tnro.roadnode_spokestart (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.roadnode ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnro.roadnode_spokestart OWNER TO elf_admin;

CREATE TABLE tnro.roadnode_geographicalname_spelling (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.roadnode ON DELETE CASCADE,
    num integer not null,
    geographicalname_spellingofname_text text,
    geographicalname_spellingofname_script text,
    geographicalname_spellingofname_script_nilreason text,
    geographicalname_spellingofname_script_nil boolean,
    geographicalname_spellingofname_transliterationscheme text,
    geographicalname_spellingofname_transliterationscheme_nilreason text,
    geographicalname_spellingofname_transliterationscheme_nil boolean
);
ALTER TABLE tnro.roadnode_geographicalname_spelling OWNER TO elf_admin;

CREATE TABLE tnro.roadservicearea (
    gml_id text,
    identifier text,
    identifier_codespace text,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    geometry_nilreason text,
    geometry_remoteschema text,
    geometry_owns boolean,
    geographicalname_nilreason text,
    geographicalname_nil boolean,
    geographicalname_language text,
    geographicalname_language_nilreason text,
    geographicalname_language_nil boolean,
    geographicalname_nativeness_owns boolean,
    geographicalname_nativeness_nilreason text,
    geographicalname_nativeness_remoteschema text,
    geographicalname_nativeness_nil boolean,
    geographicalname_nativeness_fk text,
    geographicalname_nativeness_href text,
    geographicalname_namestatus_owns boolean,
    geographicalname_namestatus_nilreason text,
    geographicalname_namestatus_remoteschema text,
    geographicalname_namestatus_nil boolean,
    geographicalname_namestatus_fk text,
    geographicalname_namestatus_href text,
    geographicalname_sourceofname text,
    geographicalname_sourceofname_nilreason text,
    geographicalname_sourceofname_nil boolean,
    geographicalname_pronunciation_nilreason text,
    geographicalname_pronunciation_nil boolean,
    geographicalname_pronunciation_soundlink text,
    geographicalname_pronunciation_soundlink_nilreason text,
    geographicalname_pronunciation_soundlink_nil boolean,
    geographicalname_pronunciation_ipa text,
    geographicalname_pronunciation_ipa_nilreason text,
    geographicalname_pronunciation_ipa_nil boolean,
    geographicalname_grammaticalgender_owns boolean,
    geographicalname_grammaticalgender_nilreason text,
    geographicalname_grammaticalgender_remoteschema text,
    geographicalname_grammaticalgender_nil boolean,
    geographicalname_grammaticalgender_fk text,
    geographicalname_grammaticalgender_href text,
    geographicalname_grammaticalnumber_owns boolean,
    geographicalname_grammaticalnumber_nilreason text,
    geographicalname_grammaticalnumber_remoteschema text,
    geographicalname_grammaticalnumber_nil boolean,
    geographicalname_grammaticalnumber_fk text,
    geographicalname_grammaticalnumber_href text,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    CONSTRAINT roadservicearea_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnro.roadservicearea OWNER TO elf_admin;

CREATE TABLE tnro.roadservicearea_innetwork (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.roadservicearea ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnro.roadservicearea_innetwork OWNER TO elf_admin;

SELECT ADDGEOMETRYCOLUMN('tnro', 'roadservicearea','geometry_value','4258','GEOMETRY', 2);
CREATE INDEX roadservicearea_geometry_idx ON tnro.roadservicearea USING GIST (geometry_value);

CREATE TABLE tnro.roadservicearea_geographicalname_spelling (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.roadservicearea ON DELETE CASCADE,
    num integer not null,
    geographicalname_spellingofname_text text,
    geographicalname_spellingofname_script text,
    geographicalname_spellingofname_script_nilreason text,
    geographicalname_spellingofname_script_nil boolean,
    geographicalname_spellingofname_transliterationscheme text,
    geographicalname_spellingofname_transliterationscheme_nilreason text,
    geographicalname_spellingofname_transliterationscheme_nil boolean
);
ALTER TABLE tnro.roadservicearea_geographicalname_spelling OWNER TO elf_admin;

CREATE TABLE tnro.roadservicetype (
    gml_id text,
    identifier text,
    identifier_codespace text,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    type_owns boolean,
    type_nilreason text,
    type_remoteschema text,
    type_fk text,
    type_href text,
    CONSTRAINT roadservicetype_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnro.roadservicetype OWNER TO elf_admin;

CREATE TABLE tnro.roadservicetype_networkref (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.roadservicetype ON DELETE CASCADE,
    num integer not null,
    nilreason text,
    nil boolean,
    simplelinearreference_element_owns boolean,
    simplelinearreference_element_nilreason text,
    simplelinearreference_element_remoteschema text,
    simplelinearreference_element_fk text,
    simplelinearreference_element_href text,
    simplelinearreference_applicabledirection_owns boolean,
    simplelinearreference_applicabledirection_nilreason text,
    simplelinearreference_applicabledirection_remoteschema text,
    simplelinearreference_applicabledirection_nil boolean,
    simplelinearreference_applicabledirection_fk text,
    simplelinearreference_applicabledirection_href text,
    simplelinearreference_fromposition numeric,
    simplelinearreference_fromposition_uom text,
    simplelinearreference_toposition numeric,
    simplelinearreference_toposition_uom text,
    simplelinearreference_offset numeric,
    simplelinearreference_offset_nilreason text,
    simplelinearreference_offset_uom text,
    simplelinearreference_offset_nil boolean,
    simplepointreference_element_owns boolean,
    simplepointreference_element_nilreason text,
    simplepointreference_element_remoteschema text,
    simplepointreference_element_fk text,
    simplepointreference_element_href text,
    simplepointreference_applicabledirection_owns boolean,
    simplepointreference_applicabledirection_nilreason text,
    simplepointreference_applicabledirection_remoteschema text,
    simplepointreference_applicabledirection_nil boolean,
    simplepointreference_applicabledirection_fk text,
    simplepointreference_applicabledirection_href text,
    simplepointreference_atposition numeric,
    simplepointreference_atposition_uom text,
    simplepointreference_offset numeric,
    simplepointreference_offset_nilreason text,
    simplepointreference_offset_uom text,
    simplepointreference_offset_nil boolean,
    linkreference_element_owns boolean,
    linkreference_element_nilreason text,
    linkreference_element_remoteschema text,
    linkreference_element_fk text,
    linkreference_element_href text,
    linkreference_applicabledirection_owns boolean,
    linkreference_applicabledirection_nilreason text,
    linkreference_applicabledirection_remoteschema text,
    linkreference_applicabledirection_nil boolean,
    linkreference_applicabledirection_fk text,
    linkreference_applicabledirection_href text,
    networkreference_element_owns boolean,
    networkreference_element_nilreason text,
    networkreference_element_remoteschema text,
    networkreference_element_fk text,
    networkreference_element_href text
);
ALTER TABLE tnro.roadservicetype_networkref OWNER TO elf_admin;

CREATE TABLE tnro.roadservicetype_availablefacility (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.roadservicetype ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    fk text,
    href text
);
ALTER TABLE tnro.roadservicetype_availablefacility OWNER TO elf_admin;

CREATE TABLE tnro.roadsurfacecategory (
    gml_id text,
    identifier text,
    identifier_codespace text,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    surfacecategory_owns boolean,
    surfacecategory_nilreason text,
    surfacecategory_remoteschema text,
    surfacecategory_fk text,
    surfacecategory_href text,
    CONSTRAINT roadsurfacecategory_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnro.roadsurfacecategory OWNER TO elf_admin;

CREATE TABLE tnro.roadsurfacecategory_networkref (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.roadsurfacecategory ON DELETE CASCADE,
    num integer not null,
    nilreason text,
    nil boolean,
    simplelinearreference_element_owns boolean,
    simplelinearreference_element_nilreason text,
    simplelinearreference_element_remoteschema text,
    simplelinearreference_element_fk text,
    simplelinearreference_element_href text,
    simplelinearreference_applicabledirection_owns boolean,
    simplelinearreference_applicabledirection_nilreason text,
    simplelinearreference_applicabledirection_remoteschema text,
    simplelinearreference_applicabledirection_nil boolean,
    simplelinearreference_applicabledirection_fk text,
    simplelinearreference_applicabledirection_href text,
    simplelinearreference_fromposition numeric,
    simplelinearreference_fromposition_uom text,
    simplelinearreference_toposition numeric,
    simplelinearreference_toposition_uom text,
    simplelinearreference_offset numeric,
    simplelinearreference_offset_nilreason text,
    simplelinearreference_offset_uom text,
    simplelinearreference_offset_nil boolean,
    simplepointreference_element_owns boolean,
    simplepointreference_element_nilreason text,
    simplepointreference_element_remoteschema text,
    simplepointreference_element_fk text,
    simplepointreference_element_href text,
    simplepointreference_applicabledirection_owns boolean,
    simplepointreference_applicabledirection_nilreason text,
    simplepointreference_applicabledirection_remoteschema text,
    simplepointreference_applicabledirection_nil boolean,
    simplepointreference_applicabledirection_fk text,
    simplepointreference_applicabledirection_href text,
    simplepointreference_atposition numeric,
    simplepointreference_atposition_uom text,
    simplepointreference_offset numeric,
    simplepointreference_offset_nilreason text,
    simplepointreference_offset_uom text,
    simplepointreference_offset_nil boolean,
    linkreference_element_owns boolean,
    linkreference_element_nilreason text,
    linkreference_element_remoteschema text,
    linkreference_element_fk text,
    linkreference_element_href text,
    linkreference_applicabledirection_owns boolean,
    linkreference_applicabledirection_nilreason text,
    linkreference_applicabledirection_remoteschema text,
    linkreference_applicabledirection_nil boolean,
    linkreference_applicabledirection_fk text,
    linkreference_applicabledirection_href text,
    networkreference_element_owns boolean,
    networkreference_element_nilreason text,
    networkreference_element_remoteschema text,
    networkreference_element_fk text,
    networkreference_element_href text
);
ALTER TABLE tnro.roadsurfacecategory_networkref OWNER TO elf_admin;

CREATE TABLE tnro.roadwidth (
    gml_id text,
    identifier text,
    identifier_codespace text,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    measuredroadpart_owns boolean,
    measuredroadpart_nilreason text,
    measuredroadpart_remoteschema text,
    measuredroadpart_nil boolean,
    measuredroadpart_fk text,
    measuredroadpart_href text,
    width numeric,
    width_uom text,
    CONSTRAINT roadwidth_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnro.roadwidth OWNER TO elf_admin;

CREATE TABLE tnro.roadwidth_networkref (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.roadwidth ON DELETE CASCADE,
    num integer not null,
    nilreason text,
    nil boolean,
    simplelinearreference_element_owns boolean,
    simplelinearreference_element_nilreason text,
    simplelinearreference_element_remoteschema text,
    simplelinearreference_element_fk text,
    simplelinearreference_element_href text,
    simplelinearreference_applicabledirection_owns boolean,
    simplelinearreference_applicabledirection_nilreason text,
    simplelinearreference_applicabledirection_remoteschema text,
    simplelinearreference_applicabledirection_nil boolean,
    simplelinearreference_applicabledirection_fk text,
    simplelinearreference_applicabledirection_href text,
    simplelinearreference_fromposition numeric,
    simplelinearreference_fromposition_uom text,
    simplelinearreference_toposition numeric,
    simplelinearreference_toposition_uom text,
    simplelinearreference_offset numeric,
    simplelinearreference_offset_nilreason text,
    simplelinearreference_offset_uom text,
    simplelinearreference_offset_nil boolean,
    simplepointreference_element_owns boolean,
    simplepointreference_element_nilreason text,
    simplepointreference_element_remoteschema text,
    simplepointreference_element_fk text,
    simplepointreference_element_href text,
    simplepointreference_applicabledirection_owns boolean,
    simplepointreference_applicabledirection_nilreason text,
    simplepointreference_applicabledirection_remoteschema text,
    simplepointreference_applicabledirection_nil boolean,
    simplepointreference_applicabledirection_fk text,
    simplepointreference_applicabledirection_href text,
    simplepointreference_atposition numeric,
    simplepointreference_atposition_uom text,
    simplepointreference_offset numeric,
    simplepointreference_offset_nilreason text,
    simplepointreference_offset_uom text,
    simplepointreference_offset_nil boolean,
    linkreference_element_owns boolean,
    linkreference_element_nilreason text,
    linkreference_element_remoteschema text,
    linkreference_element_fk text,
    linkreference_element_href text,
    linkreference_applicabledirection_owns boolean,
    linkreference_applicabledirection_nilreason text,
    linkreference_applicabledirection_remoteschema text,
    linkreference_applicabledirection_nil boolean,
    linkreference_applicabledirection_fk text,
    linkreference_applicabledirection_href text,
    networkreference_element_owns boolean,
    networkreference_element_nilreason text,
    networkreference_element_remoteschema text,
    networkreference_element_fk text,
    networkreference_element_href text
);
ALTER TABLE tnro.roadwidth_networkref OWNER TO elf_admin;

CREATE TABLE tnro.speedlimit (
    gml_id text,
    identifier text,
    identifier_codespace text,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    areacondition_owns boolean,
    areacondition_nilreason text,
    areacondition_remoteschema text,
    areacondition_nil boolean,
    areacondition_fk text,
    areacondition_href text,
    direction_owns boolean,
    direction_nilreason text,
    direction_remoteschema text,
    direction_nil boolean,
    direction_fk text,
    direction_href text,
    laneextension integer,
    laneextension_nilreason text,
    laneextension_nil boolean,
    speedlimitminmaxtype text,
    speedlimitsource_owns boolean,
    speedlimitsource_nilreason text,
    speedlimitsource_remoteschema text,
    speedlimitsource_nil boolean,
    speedlimitsource_fk text,
    speedlimitsource_href text,
    speedlimitvalue numeric,
    speedlimitvalue_uom text,
    startlane integer,
    startlane_nilreason text,
    startlane_nil boolean,
    vehicletype_owns boolean,
    vehicletype_nilreason text,
    vehicletype_remoteschema text,
    vehicletype_nil boolean,
    vehicletype_fk text,
    vehicletype_href text,
    weathercondition_owns boolean,
    weathercondition_nilreason text,
    weathercondition_remoteschema text,
    weathercondition_nil boolean,
    weathercondition_fk text,
    weathercondition_href text,
    CONSTRAINT speedlimit_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnro.speedlimit OWNER TO elf_admin;

CREATE TABLE tnro.speedlimit_networkref (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.speedlimit ON DELETE CASCADE,
    num integer not null,
    nilreason text,
    nil boolean,
    simplelinearreference_element_owns boolean,
    simplelinearreference_element_nilreason text,
    simplelinearreference_element_remoteschema text,
    simplelinearreference_element_fk text,
    simplelinearreference_element_href text,
    simplelinearreference_applicabledirection_owns boolean,
    simplelinearreference_applicabledirection_nilreason text,
    simplelinearreference_applicabledirection_remoteschema text,
    simplelinearreference_applicabledirection_nil boolean,
    simplelinearreference_applicabledirection_fk text,
    simplelinearreference_applicabledirection_href text,
    simplelinearreference_fromposition numeric,
    simplelinearreference_fromposition_uom text,
    simplelinearreference_toposition numeric,
    simplelinearreference_toposition_uom text,
    simplelinearreference_offset numeric,
    simplelinearreference_offset_nilreason text,
    simplelinearreference_offset_uom text,
    simplelinearreference_offset_nil boolean,
    simplepointreference_element_owns boolean,
    simplepointreference_element_nilreason text,
    simplepointreference_element_remoteschema text,
    simplepointreference_element_fk text,
    simplepointreference_element_href text,
    simplepointreference_applicabledirection_owns boolean,
    simplepointreference_applicabledirection_nilreason text,
    simplepointreference_applicabledirection_remoteschema text,
    simplepointreference_applicabledirection_nil boolean,
    simplepointreference_applicabledirection_fk text,
    simplepointreference_applicabledirection_href text,
    simplepointreference_atposition numeric,
    simplepointreference_atposition_uom text,
    simplepointreference_offset numeric,
    simplepointreference_offset_nilreason text,
    simplepointreference_offset_uom text,
    simplepointreference_offset_nil boolean,
    linkreference_element_owns boolean,
    linkreference_element_nilreason text,
    linkreference_element_remoteschema text,
    linkreference_element_fk text,
    linkreference_element_href text,
    linkreference_applicabledirection_owns boolean,
    linkreference_applicabledirection_nilreason text,
    linkreference_applicabledirection_remoteschema text,
    linkreference_applicabledirection_nil boolean,
    linkreference_applicabledirection_fk text,
    linkreference_applicabledirection_href text,
    networkreference_element_owns boolean,
    networkreference_element_nilreason text,
    networkreference_element_remoteschema text,
    networkreference_element_fk text,
    networkreference_element_href text
);
ALTER TABLE tnro.speedlimit_networkref OWNER TO elf_admin;

CREATE TABLE tnro.vehicletrafficarea (
    gml_id text,
    identifier text,
    identifier_codespace text,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    geometry_nilreason text,
    geometry_remoteschema text,
    geometry_owns boolean,
    geographicalname_nilreason text,
    geographicalname_nil boolean,
    geographicalname_language text,
    geographicalname_language_nilreason text,
    geographicalname_language_nil boolean,
    geographicalname_nativeness_owns boolean,
    geographicalname_nativeness_nilreason text,
    geographicalname_nativeness_remoteschema text,
    geographicalname_nativeness_nil boolean,
    geographicalname_nativeness_fk text,
    geographicalname_nativeness_href text,
    geographicalname_namestatus_owns boolean,
    geographicalname_namestatus_nilreason text,
    geographicalname_namestatus_remoteschema text,
    geographicalname_namestatus_nil boolean,
    geographicalname_namestatus_fk text,
    geographicalname_namestatus_href text,
    geographicalname_sourceofname text,
    geographicalname_sourceofname_nilreason text,
    geographicalname_sourceofname_nil boolean,
    geographicalname_pronunciation_nilreason text,
    geographicalname_pronunciation_nil boolean,
    geographicalname_pronunciation_soundlink text,
    geographicalname_pronunciation_soundlink_nilreason text,
    geographicalname_pronunciation_soundlink_nil boolean,
    geographicalname_pronunciation_ipa text,
    geographicalname_pronunciation_ipa_nilreason text,
    geographicalname_pronunciation_ipa_nil boolean,
    geographicalname_grammaticalgender_owns boolean,
    geographicalname_grammaticalgender_nilreason text,
    geographicalname_grammaticalgender_remoteschema text,
    geographicalname_grammaticalgender_nil boolean,
    geographicalname_grammaticalgender_fk text,
    geographicalname_grammaticalgender_href text,
    geographicalname_grammaticalnumber_owns boolean,
    geographicalname_grammaticalnumber_nilreason text,
    geographicalname_grammaticalnumber_remoteschema text,
    geographicalname_grammaticalnumber_nil boolean,
    geographicalname_grammaticalnumber_fk text,
    geographicalname_grammaticalnumber_href text,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    CONSTRAINT vehicletrafficarea_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnro.vehicletrafficarea OWNER TO elf_admin;

CREATE TABLE tnro.vehicletrafficarea_innetwork (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.vehicletrafficarea ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnro.vehicletrafficarea_innetwork OWNER TO elf_admin;

SELECT ADDGEOMETRYCOLUMN('tnro', 'vehicletrafficarea','geometry_value','4258','GEOMETRY', 2);
CREATE INDEX vehicletrafficarea_geometry_idx ON tnro.vehicletrafficarea USING GIST (geometry_value);

CREATE TABLE tnro.vehicletrafficarea_geographicalname_spelling (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.vehicletrafficarea ON DELETE CASCADE,
    num integer not null,
    geographicalname_spellingofname_text text,
    geographicalname_spellingofname_script text,
    geographicalname_spellingofname_script_nilreason text,
    geographicalname_spellingofname_script_nil boolean,
    geographicalname_spellingofname_transliterationscheme text,
    geographicalname_spellingofname_transliterationscheme_nilreason text,
    geographicalname_spellingofname_transliterationscheme_nil boolean
);
ALTER TABLE tnro.vehicletrafficarea_geographicalname_spelling OWNER TO elf_admin;

CREATE TABLE tnro.interchangepoint (
    gml_id text,
    identifier text,
    identifier_codespace text,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    geographicalname_nilreason text,
    geographicalname_nil boolean,
    geographicalname_language text,
    geographicalname_language_nilreason text,
    geographicalname_language_nil boolean,
    geographicalname_nativeness_owns boolean,
    geographicalname_nativeness_nilreason text,
    geographicalname_nativeness_remoteschema text,
    geographicalname_nativeness_nil boolean,
    geographicalname_nativeness_fk text,
    geographicalname_nativeness_href text,
    geographicalname_namestatus_owns boolean,
    geographicalname_namestatus_nilreason text,
    geographicalname_namestatus_remoteschema text,
    geographicalname_namestatus_nil boolean,
    geographicalname_namestatus_fk text,
    geographicalname_namestatus_href text,
    geographicalname_sourceofname text,
    geographicalname_sourceofname_nilreason text,
    geographicalname_sourceofname_nil boolean,
    geographicalname_pronunciation_nilreason text,
    geographicalname_pronunciation_nil boolean,
    geographicalname_pronunciation_soundlink text,
    geographicalname_pronunciation_soundlink_nilreason text,
    geographicalname_pronunciation_soundlink_nil boolean,
    geographicalname_pronunciation_ipa text,
    geographicalname_pronunciation_ipa_nilreason text,
    geographicalname_pronunciation_ipa_nil boolean,
    geographicalname_grammaticalgender_owns boolean,
    geographicalname_grammaticalgender_nilreason text,
    geographicalname_grammaticalgender_remoteschema text,
    geographicalname_grammaticalgender_nil boolean,
    geographicalname_grammaticalgender_fk text,
    geographicalname_grammaticalgender_href text,
    geographicalname_grammaticalnumber_owns boolean,
    geographicalname_grammaticalnumber_nilreason text,
    geographicalname_grammaticalnumber_remoteschema text,
    geographicalname_grammaticalnumber_nil boolean,
    geographicalname_grammaticalnumber_fk text,
    geographicalname_grammaticalnumber_href text,
    geometry_nilreason text,
    geometry_remoteschema text,
    geometry_owns boolean,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    typeofinterchange_owns boolean,
    typeofinterchange_nilreason text,
    typeofinterchange_remoteschema text,
    typeofinterchange_fk text,
    typeofinterchange_href text,
    CONSTRAINT interchangepoint_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnro.interchangepoint OWNER TO elf_admin;

CREATE TABLE tnro.interchangepoint_innetwork (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.interchangepoint ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnro.interchangepoint_innetwork OWNER TO elf_admin;

CREATE TABLE tnro.interchangepoint_geographicalname_spelling (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.interchangepoint ON DELETE CASCADE,
    num integer not null,
    geographicalname_spellingofname_text text,
    geographicalname_spellingofname_script text,
    geographicalname_spellingofname_script_nilreason text,
    geographicalname_spellingofname_script_nil boolean,
    geographicalname_spellingofname_transliterationscheme text,
    geographicalname_spellingofname_transliterationscheme_nilreason text,
    geographicalname_spellingofname_transliterationscheme_nil boolean
);
ALTER TABLE tnro.interchangepoint_geographicalname_spelling OWNER TO elf_admin;

SELECT ADDGEOMETRYCOLUMN('tnro', 'interchangepoint','geometry_value','4258','GEOMETRY', 2);
CREATE INDEX interchangepoint_geometry_idx ON tnro.interchangepoint USING GIST (geometry_value);

CREATE TABLE tnro.roadlink (
    gml_id text,
    identifier text,
    identifier_codespace text,
    beginlifespanversion timestamp,
    beginlifespanversion_nilreason text,
    beginlifespanversion_nil boolean,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_nilreason text,
    inspireid_identifier_versionid_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_nilreason text,
    endlifespanversion_nil boolean,
    centrelinegeometry_nilreason text,
    centrelinegeometry_remoteschema text,
    centrelinegeometry_owns boolean,
    fictitious boolean,
    endnode_owns boolean,
    endnode_nilreason text,
    endnode_remoteschema text,
    endnode_fk text,
    endnode_href text,
    startnode_owns boolean,
    startnode_nilreason text,
    startnode_remoteschema text,
    startnode_fk text,
    startnode_href text,
    geographicalname_nilreason text,
    geographicalname_nil boolean,
    geographicalname_language text,
    geographicalname_language_nilreason text,
    geographicalname_language_nil boolean,
    geographicalname_nativeness_owns boolean,
    geographicalname_nativeness_nilreason text,
    geographicalname_nativeness_remoteschema text,
    geographicalname_nativeness_nil boolean,
    geographicalname_nativeness_fk text,
    geographicalname_nativeness_href text,
    geographicalname_namestatus_owns boolean,
    geographicalname_namestatus_nilreason text,
    geographicalname_namestatus_remoteschema text,
    geographicalname_namestatus_nil boolean,
    geographicalname_namestatus_fk text,
    geographicalname_namestatus_href text,
    geographicalname_sourceofname text,
    geographicalname_sourceofname_nilreason text,
    geographicalname_sourceofname_nil boolean,
    geographicalname_pronunciation_nilreason text,
    geographicalname_pronunciation_nil boolean,
    geographicalname_pronunciation_soundlink text,
    geographicalname_pronunciation_soundlink_nilreason text,
    geographicalname_pronunciation_soundlink_nil boolean,
    geographicalname_pronunciation_ipa text,
    geographicalname_pronunciation_ipa_nilreason text,
    geographicalname_pronunciation_ipa_nil boolean,
    geographicalname_grammaticalgender_owns boolean,
    geographicalname_grammaticalgender_nilreason text,
    geographicalname_grammaticalgender_remoteschema text,
    geographicalname_grammaticalgender_nil boolean,
    geographicalname_grammaticalgender_fk text,
    geographicalname_grammaticalgender_href text,
    geographicalname_grammaticalnumber_owns boolean,
    geographicalname_grammaticalnumber_nilreason text,
    geographicalname_grammaticalnumber_remoteschema text,
    geographicalname_grammaticalnumber_nil boolean,
    geographicalname_grammaticalnumber_fk text,
    geographicalname_grammaticalnumber_href text,
    validfrom timestamp,
    validfrom_nilreason text,
    validfrom_nil boolean,
    validto timestamp,
    validto_nilreason text,
    validto_nil boolean,
    transeuropeantransportnetwork boolean,
    CONSTRAINT roadlink_pkey PRIMARY KEY (gml_id)
);
ALTER TABLE tnro.roadlink OWNER TO elf_admin;

CREATE TABLE tnro.roadlink_innetwork (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.roadlink ON DELETE CASCADE,
    num integer not null,
    owns boolean,
    nilreason text,
    remoteschema text,
    nil boolean,
    fk text,
    href text
);
ALTER TABLE tnro.roadlink_innetwork OWNER TO elf_admin;

SELECT ADDGEOMETRYCOLUMN('tnro', 'roadlink','centrelinegeometry_value','4258','GEOMETRY', 2);
CREATE INDEX roadlink_geometry_idx ON tnro.roadlink USING GIST (centrelinegeometry_value);

CREATE TABLE tnro.roadlink_geographicalname_spelling (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES tnro.roadlink ON DELETE CASCADE,
    num integer not null,
    geographicalname_spellingofname_text text,
    geographicalname_spellingofname_script text,
    geographicalname_spellingofname_script_nilreason text,
    geographicalname_spellingofname_script_nil boolean,
    geographicalname_spellingofname_transliterationscheme text,
    geographicalname_spellingofname_transliterationscheme_nilreason text,
    geographicalname_spellingofname_transliterationscheme_nil boolean
);
ALTER TABLE tnro.roadlink_geographicalname_spelling OWNER TO elf_admin;
